// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:redis_ffi/redis_ffi.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<redisReader> Function(ffi.Pointer<redisReplyObjectFunctions>)
>()
external ffi.Pointer<redisReader> redisReaderCreateWithFunctions(
  ffi.Pointer<redisReplyObjectFunctions> fn,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisReader>)>()
external void redisReaderFree(ffi.Pointer<redisReader> r);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<redisReader>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int redisReaderFeed(
  ffi.Pointer<redisReader> r,
  ffi.Pointer<ffi.Char> buf,
  int len,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<redisReader>, ffi.Pointer<ffi.Pointer<ffi.Void>>)
>()
external int redisReaderGetReply(
  ffi.Pointer<redisReader> r,
  ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
);

@ffi.Native<sds Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external sds sdsnewlen(ffi.Pointer<ffi.Void> init, int initlen);

@ffi.Native<sds Function(ffi.Pointer<ffi.Char>)>()
external sds sdsnew(ffi.Pointer<ffi.Char> init);

@ffi.Native<sds Function()>()
external sds sdsempty();

@ffi.Native<sds Function(sds)>()
external sds sdsdup(sds s);

@ffi.Native<ffi.Void Function(sds)>()
external void sdsfree(sds s);

@ffi.Native<sds Function(sds, ffi.Size)>()
external sds sdsgrowzero(sds s, int len);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Void>, ffi.Size)>()
external sds sdscatlen(sds s, ffi.Pointer<ffi.Void> t, int len);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>)>()
external sds sdscat(sds s, ffi.Pointer<ffi.Char> t);

@ffi.Native<sds Function(sds, sds)>()
external sds sdscatsds(sds s, sds t);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>()
external sds sdscpylen(sds s, ffi.Pointer<ffi.Char> t, int len);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>)>()
external sds sdscpy(sds s, ffi.Pointer<ffi.Char> t);

@ffi.Native<
  sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
>()
external sds sdscatvprintf(
  sds s,
  ffi.Pointer<ffi.Char> fmt,
  ffi.Pointer<__va_list_tag> ap,
);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>)>()
external sds sdscatprintf(sds s, ffi.Pointer<ffi.Char> fmt);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>)>()
external sds sdscatfmt(sds s, ffi.Pointer<ffi.Char> fmt);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>)>()
external sds sdstrim(sds s, ffi.Pointer<ffi.Char> cset);

@ffi.Native<ffi.Int Function(sds, ssize_t, ssize_t)>()
external int sdsrange(sds s, int start, int end);

@ffi.Native<ffi.Void Function(sds)>()
external void sdsupdatelen(sds s);

@ffi.Native<ffi.Void Function(sds)>()
external void sdsclear(sds s);

@ffi.Native<ffi.Int Function(sds, sds)>()
external int sdscmp(sds s1, sds s2);

@ffi.Native<
  ffi.Pointer<sds> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
  )
>()
external ffi.Pointer<sds> sdssplitlen(
  ffi.Pointer<ffi.Char> s,
  int len,
  ffi.Pointer<ffi.Char> sep,
  int seplen,
  ffi.Pointer<ffi.Int> count,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<sds>, ffi.Int)>()
external void sdsfreesplitres(ffi.Pointer<sds> tokens, int count);

@ffi.Native<ffi.Void Function(sds)>()
external void sdstolower(sds s);

@ffi.Native<ffi.Void Function(sds)>()
external void sdstoupper(sds s);

@ffi.Native<sds Function(ffi.LongLong)>()
external sds sdsfromlonglong(int value);

@ffi.Native<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>()
external sds sdscatrepr(sds s, ffi.Pointer<ffi.Char> p, int len);

@ffi.Native<
  ffi.Pointer<sds> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
>()
external ffi.Pointer<sds> sdssplitargs(
  ffi.Pointer<ffi.Char> line,
  ffi.Pointer<ffi.Int> argc,
);

@ffi.Native<
  sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external sds sdsmapchars(
  sds s,
  ffi.Pointer<ffi.Char> from,
  ffi.Pointer<ffi.Char> to,
  int setlen,
);

@ffi.Native<
  sds Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external sds sdsjoin(
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  int argc,
  ffi.Pointer<ffi.Char> sep,
);

@ffi.Native<
  sds Function(ffi.Pointer<sds>, ffi.Int, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external sds sdsjoinsds(
  ffi.Pointer<sds> argv,
  int argc,
  ffi.Pointer<ffi.Char> sep,
  int seplen,
);

@ffi.Native<sds Function(sds, ffi.Size)>()
external sds sdsMakeRoomFor(sds s, int addlen);

@ffi.Native<ffi.Void Function(sds, ffi.Int)>()
external void sdsIncrLen(sds s, int incr);

@ffi.Native<sds Function(sds)>()
external sds sdsRemoveFreeSpace(sds s);

@ffi.Native<ffi.Size Function(sds)>()
external int sdsAllocSize(sds s);

@ffi.Native<ffi.Pointer<ffi.Void> Function(sds)>()
external ffi.Pointer<ffi.Void> sdsAllocPtr(sds s);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Size)>()
external ffi.Pointer<ffi.Void> sds_malloc(int size);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external ffi.Pointer<ffi.Void> sds_realloc(ffi.Pointer<ffi.Void> ptr, int size);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sds_free(ffi.Pointer<ffi.Void> ptr);

@ffi.Native<hiredisAllocFuncs>()
external hiredisAllocFuncs hiredisAllocFns;

@ffi.Native<ffi.Pointer<redisReader> Function()>()
external ffi.Pointer<redisReader> redisReaderCreate();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void freeReplyObject(ffi.Pointer<ffi.Void> reply);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int redisvFormatCommand(
  ffi.Pointer<ffi.Pointer<ffi.Char>> target,
  ffi.Pointer<ffi.Char> format,
  ffi.Pointer<__va_list_tag> ap,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
>()
external int redisFormatCommand(
  ffi.Pointer<ffi.Pointer<ffi.Char>> target,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
  ffi.LongLong Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int redisFormatCommandArgv(
  ffi.Pointer<ffi.Pointer<ffi.Char>> target,
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Size> argvlen,
);

@ffi.Native<
  ffi.LongLong Function(
    ffi.Pointer<sds>,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int redisFormatSdsCommandArgv(
  ffi.Pointer<sds> target,
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Size> argvlen,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void redisFreeCommand(ffi.Pointer<ffi.Char> cmd);

@ffi.Native<ffi.Void Function(sds)>()
external void redisFreeSdsCommand(sds cmd);

@ffi.Native<ffi.Pointer<redisContext> Function(ffi.Pointer<redisOptions>)>()
external ffi.Pointer<redisContext> redisConnectWithOptions(
  ffi.Pointer<redisOptions> options,
);

@ffi.Native<
  ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
>()
external ffi.Pointer<redisContext> redisConnect(
  ffi.Pointer<ffi.Char> ip,
  int port,
);

@ffi.Native<
  ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, ffi.Int, timeval)
>()
external ffi.Pointer<redisContext> redisConnectWithTimeout(
  ffi.Pointer<ffi.Char> ip,
  int port,
  timeval tv,
);

@ffi.Native<
  ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
>()
external ffi.Pointer<redisContext> redisConnectNonBlock(
  ffi.Pointer<ffi.Char> ip,
  int port,
);

@ffi.Native<
  ffi.Pointer<redisContext> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<redisContext> redisConnectBindNonBlock(
  ffi.Pointer<ffi.Char> ip,
  int port,
  ffi.Pointer<ffi.Char> source_addr,
);

@ffi.Native<
  ffi.Pointer<redisContext> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<redisContext> redisConnectBindNonBlockWithReuse(
  ffi.Pointer<ffi.Char> ip,
  int port,
  ffi.Pointer<ffi.Char> source_addr,
);

@ffi.Native<ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<redisContext> redisConnectUnix(ffi.Pointer<ffi.Char> path);

@ffi.Native<
  ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, timeval)
>()
external ffi.Pointer<redisContext> redisConnectUnixWithTimeout(
  ffi.Pointer<ffi.Char> path,
  timeval tv,
);

@ffi.Native<ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<redisContext> redisConnectUnixNonBlock(
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Pointer<redisContext> Function(redisFD)>()
external ffi.Pointer<redisContext> redisConnectFd(int fd);

/// Reconnect the given context using the saved information.
///
/// This re-uses the exact same connect options as in the initial connection.
/// host, ip (or path), timeout and bind address are reused,
/// flags are used unmodified from the existing context.
///
/// Returns REDIS_OK on successful connect or REDIS_ERR otherwise.
@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>)>()
external int redisReconnect(ffi.Pointer<redisContext> c);

@ffi.Native<
  ffi.Pointer<redisPushFn> Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<redisPushFn>,
  )
>()
external ffi.Pointer<redisPushFn> redisSetPushCallback(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<redisPushFn> fn,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>, timeval)>()
external int redisSetTimeout(ffi.Pointer<redisContext> c, timeval tv);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>)>()
external int redisEnableKeepAlive(ffi.Pointer<redisContext> c);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>, ffi.Int)>()
external int redisEnableKeepAliveWithInterval(
  ffi.Pointer<redisContext> c,
  int interval,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>, ffi.UnsignedInt)>()
external int redisSetTcpUserTimeout(ffi.Pointer<redisContext> c, int timeout);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisContext>)>()
external void redisFree(ffi.Pointer<redisContext> c);

@ffi.Native<redisFD Function(ffi.Pointer<redisContext>)>()
external int redisFreeKeepFd(ffi.Pointer<redisContext> c);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>)>()
external int redisBufferRead(ffi.Pointer<redisContext> c);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Int>)>()
external int redisBufferWrite(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Int> done,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
  )
>()
external int redisGetReply(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
  )
>()
external int redisGetReplyFromReader(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int redisAppendFormattedCommand(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Char> cmd,
  int len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int redisvAppendCommand(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Char> format,
  ffi.Pointer<__va_list_tag> ap,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Char>)
>()
external int redisAppendCommand(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisContext>,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int redisAppendCommandArgv(
  ffi.Pointer<redisContext> c,
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Size> argvlen,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external ffi.Pointer<ffi.Void> redisvCommand(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Char> format,
  ffi.Pointer<__va_list_tag> ap,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<redisContext>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Void> redisCommand(
  ffi.Pointer<redisContext> c,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(
    ffi.Pointer<redisContext>,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external ffi.Pointer<ffi.Void> redisCommandArgv(
  ffi.Pointer<redisContext> c,
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Size> argvlen,
);

@ffi.Native<
  ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<redisOptions>)
>()
external ffi.Pointer<redisAsyncContext> redisAsyncConnectWithOptions(
  ffi.Pointer<redisOptions> options,
);

@ffi.Native<
  ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
>()
external ffi.Pointer<redisAsyncContext> redisAsyncConnect(
  ffi.Pointer<ffi.Char> ip,
  int port,
);

@ffi.Native<
  ffi.Pointer<redisAsyncContext> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<redisAsyncContext> redisAsyncConnectBind(
  ffi.Pointer<ffi.Char> ip,
  int port,
  ffi.Pointer<ffi.Char> source_addr,
);

@ffi.Native<
  ffi.Pointer<redisAsyncContext> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<redisAsyncContext> redisAsyncConnectBindWithReuse(
  ffi.Pointer<ffi.Char> ip,
  int port,
  ffi.Pointer<ffi.Char> source_addr,
);

@ffi.Native<ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<redisAsyncContext> redisAsyncConnectUnix(
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisConnectCallback>,
  )
>()
external int redisAsyncSetConnectCallback(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisConnectCallback> fn,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisConnectCallbackNC>,
  )
>()
external int redisAsyncSetConnectCallbackNC(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisConnectCallbackNC> fn,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisDisconnectCallback>,
  )
>()
external int redisAsyncSetDisconnectCallback(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisDisconnectCallback> fn,
);

@ffi.Native<
  ffi.Pointer<redisAsyncPushFn> Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisAsyncPushFn>,
  )
>()
external ffi.Pointer<redisAsyncPushFn> redisAsyncSetPushCallback(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisAsyncPushFn> fn,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<redisAsyncContext>, timeval)>()
external int redisAsyncSetTimeout(
  ffi.Pointer<redisAsyncContext> ac,
  timeval tv,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncDisconnect(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncFree(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncHandleRead(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncHandleWrite(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncHandleTimeout(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncRead(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redisAsyncWrite(ffi.Pointer<redisAsyncContext> ac);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisCallbackFn>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<__va_list_tag>,
  )
>()
external int redisvAsyncCommand(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisCallbackFn> fn,
  ffi.Pointer<ffi.Void> privdata,
  ffi.Pointer<ffi.Char> format,
  ffi.Pointer<__va_list_tag> ap,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisCallbackFn>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
  )
>()
external int redisAsyncCommand(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisCallbackFn> fn,
  ffi.Pointer<ffi.Void> privdata,
  ffi.Pointer<ffi.Char> format,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisCallbackFn>,
    ffi.Pointer<ffi.Void>,
    ffi.Int,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int redisAsyncCommandArgv(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisCallbackFn> fn,
  ffi.Pointer<ffi.Void> privdata,
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
  ffi.Pointer<ffi.Size> argvlen,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<redisCallbackFn>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int redisAsyncFormattedCommand(
  ffi.Pointer<redisAsyncContext> ac,
  ffi.Pointer<redisCallbackFn> fn,
  ffi.Pointer<ffi.Void> privdata,
  ffi.Pointer<ffi.Char> cmd,
  int len,
);

/// Polls the Redis async context for I/O readiness and handles events.
///
/// This function blocks until:
/// - Data is available to read
/// - The socket is ready for writing (and we have data to write)
/// - The timeout expires
/// - An error occurs
///
/// @param ctx The async context to poll.
/// @param timeout_ms Timeout in milliseconds. Use -1 for infinite wait.
/// @return Poll result code.
@ffi.Native<ffi.Int Function(ffi.Pointer<redisAsyncContext>, ffi.Int)>(
  symbol: 'redis_async_poll',
)
external int _redis_async_poll(
  ffi.Pointer<redisAsyncContext> ctx,
  int timeout_ms,
);

RedisPollResult redis_async_poll(
  ffi.Pointer<redisAsyncContext> ctx,
  int timeout_ms,
) => RedisPollResult.fromValue(_redis_async_poll(ctx, timeout_ms));

/// Runs a blocking event loop that waits for socket activity.
///
/// This function blocks on poll() waiting for I/O events and processes them.
///
/// The loop exits when:
/// - The stop_flag pointer is set to true (non-zero)
/// - The connection is closed or errors
/// - The context becomes invalid
///
/// @param ctx The async context to run the loop for.
/// @param stop_flag Pointer to a bool that Dart can set to signal stop.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Pointer<ffi.Bool>)
>()
external void redis_async_run_loop(
  ffi.Pointer<redisAsyncContext> ctx,
  ffi.Pointer<ffi.Bool> stop_flag,
);

/// Gets the file descriptor from an async context.
/// @return The fd, or -1 if the context is null or disconnected.
@ffi.Native<ffi.Int Function(ffi.Pointer<redisAsyncContext>)>()
external int redis_async_get_fd(ffi.Pointer<redisAsyncContext> ctx);

/// Checks if the async context is connected.
/// @return true if connected, false otherwise.
@ffi.Native<ffi.Bool Function(ffi.Pointer<redisAsyncContext>)>()
external bool redis_async_is_connected(ffi.Pointer<redisAsyncContext> ctx);

/// Forces a write flush - sends any pending commands immediately.
@ffi.Native<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>()
external void redis_async_flush(ffi.Pointer<redisAsyncContext> ctx);

/// Starts the event loop on a background thread.
///
/// This function spawns a new thread that runs the blocking event loop,
/// allowing the calling thread (Dart's event loop) to continue processing.
///
/// @param ctx The async context to run the loop for.
/// @param stop_flag Pointer to a bool that can be set to signal stop.
/// @return Opaque handle pointer, or NULL on failure.
@ffi.Native<
  ffi.Pointer<LoopThreadHandle> Function(
    ffi.Pointer<redisAsyncContext>,
    ffi.Pointer<ffi.Bool>,
  )
>()
external ffi.Pointer<LoopThreadHandle> redis_async_start_loop_thread(
  ffi.Pointer<redisAsyncContext> ctx,
  ffi.Pointer<ffi.Bool> stop_flag,
);

/// Stops the background loop thread and cleans up resources.
///
/// This function sets the stop flag, waits for the thread to exit,
/// and frees all associated resources.
///
/// @param handle The handle returned by redis_async_start_loop_thread.
@ffi.Native<ffi.Void Function(ffi.Pointer<LoopThreadHandle>)>()
external void redis_async_stop_loop_thread(
  ffi.Pointer<LoopThreadHandle> handle,
);

final class redisReadTask extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int elements;

  @ffi.Int()
  external int idx;

  external ffi.Pointer<ffi.Void> obj;

  external ffi.Pointer<redisReadTask> parent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redisReplyObjectFunctions extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redisReadTask>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createString;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.Size)
    >
  >
  createArray;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.LongLong)
    >
  >
  createInteger;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redisReadTask>,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createDouble;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>)
    >
  >
  createNil;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.Int)
    >
  >
  createBool;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeObject;
}

final class redisReader extends ffi.Struct {
  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  external ffi.Pointer<ffi.Char> buf;

  @ffi.Size()
  external int pos;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int maxbuf;

  @ffi.LongLong()
  external int maxelements;

  external ffi.Pointer<ffi.Pointer<redisReadTask>> task;

  @ffi.Int()
  external int tasks;

  @ffi.Int()
  external int ridx;

  external ffi.Pointer<ffi.Void> reply;

  external ffi.Pointer<redisReplyObjectFunctions> fn;

  external ffi.Pointer<ffi.Void> privdata;
}

typedef sds = ffi.Pointer<ffi.Char>;

final class __va_list_tag extends ffi.Struct {
  @ffi.UnsignedInt()
  external int gp_offset;

  @ffi.UnsignedInt()
  external int fp_offset;

  external ffi.Pointer<ffi.Void> overflow_arg_area;

  external ffi.Pointer<ffi.Void> reg_save_area;
}

typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef ssize_t = __darwin_ssize_t;

final class hiredisAllocFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>
  >
  mallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>
  >
  callocFn;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
    >
  >
  reallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>
  >
  strdupFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeFn;
}

final class redisContextFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisContext>)>
  >
  close;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privctx;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
  >
  async_read;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
  >
  async_write;

  external ffi.Pointer<
    ffi.NativeFunction<
      ssize_t Function(
        ffi.Pointer<redisContext>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  read;

  external ffi.Pointer<
    ffi.NativeFunction<ssize_t Function(ffi.Pointer<redisContext>)>
  >
  write;
}

typedef redisFD = ffi.Int;
typedef DartredisFD = int;

enum redisConnectionType {
  REDIS_CONN_TCP(0),
  REDIS_CONN_UNIX(1),
  REDIS_CONN_USERFD(2);

  final int value;
  const redisConnectionType(this.value);

  static redisConnectionType fromValue(int value) => switch (value) {
    0 => REDIS_CONN_TCP,
    1 => REDIS_CONN_UNIX,
    2 => REDIS_CONN_USERFD,
    _ => throw ArgumentError('Unknown value for redisConnectionType: $value'),
  };
}

typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __darwin_suseconds_t = __int32_t;

final class timeval extends ffi.Struct {
  @__darwin_time_t()
  external int tv_sec;

  @__darwin_suseconds_t()
  external int tv_usec;
}

final class UnnamedStruct$2 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> host;

  external ffi.Pointer<ffi.Char> source_addr;

  @ffi.Int()
  external int port;
}

final class UnnamedStruct$3 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> path;
}

final class sockaddr extends ffi.Opaque {}

typedef redisPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >;

final class redisContext extends ffi.Struct {
  external ffi.Pointer<redisContextFuncs> funcs;

  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  @redisFD()
  external int fd;

  @ffi.Int()
  external int flags;

  external ffi.Pointer<ffi.Char> obuf;

  external ffi.Pointer<redisReader> reader;

  @ffi.UnsignedInt()
  external int connection_typeAsInt;

  redisConnectionType get connection_type =>
      redisConnectionType.fromValue(connection_typeAsInt);

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedStruct$2 tcp;

  external UnnamedStruct$3 unix_sock;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<ffi.Void> privctx;

  external ffi.Pointer<redisPushFn> push_cb;
}

final class UnnamedStruct extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  cleanup;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> privdata, timeval tv)
    >
  >
  scheduleTimer;
}

typedef redisDisconnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisConnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisConnectCallbackNC =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisCallbackFn =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<redisAsyncContext>,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Void>,
      )
    >;

final class redisCallback extends ffi.Struct {
  external ffi.Pointer<redisCallback> next;

  external ffi.Pointer<redisCallbackFn> fn;

  @ffi.Int()
  external int pending_subs;

  @ffi.Int()
  external int unsubscribe_sent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redisCallbackList extends ffi.Struct {
  external ffi.Pointer<redisCallback> head;

  external ffi.Pointer<redisCallback> tail;
}

final class dict extends ffi.Opaque {}

final class UnnamedStruct$1 extends ffi.Struct {
  external redisCallbackList replies;

  external ffi.Pointer<dict> channels;

  external ffi.Pointer<dict> patterns;

  @ffi.Int()
  external int pending_unsubs;
}

typedef redisAsyncPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Pointer<ffi.Void>)
    >;

final class redisAsyncContext extends ffi.Struct {
  external redisContext c;

  @ffi.Int()
  external int err;

  external ffi.Pointer<ffi.Char> errstr;

  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  dataCleanup;

  external UnnamedStruct ev;

  external ffi.Pointer<redisDisconnectCallback> onDisconnect;

  external ffi.Pointer<redisConnectCallback> onConnect;

  external ffi.Pointer<redisConnectCallbackNC> onConnectNC;

  external redisCallbackList replies;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external UnnamedStruct$1 sub;

  external ffi.Pointer<redisAsyncPushFn> push_cb;
}

final class redisReply extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int integer;

  @ffi.Double()
  external double dval;

  @ffi.Size()
  external int len;

  external ffi.Pointer<ffi.Char> str;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> vtype;

  @ffi.Size()
  external int elements;

  external ffi.Pointer<ffi.Pointer<redisReply>> element;
}

/// use this field for tcp/ip connections
final class UnnamedStruct$4 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> source_addr;

  external ffi.Pointer<ffi.Char> ip;

  @ffi.Int()
  external int port;
}

final class UnnamedUnion extends ffi.Union {
  external UnnamedStruct$4 tcp;

  /// use this field for unix domain sockets
  external ffi.Pointer<ffi.Char> unix_socket;

  /// use this field to have hiredis operate an already-open
  /// file descriptor
  @redisFD()
  external int fd;
}

final class redisOptions extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.Int()
  external int options;

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedUnion endpoint;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<redisPushFn> push_cb;

  external ffi.Pointer<redisAsyncPushFn> async_push_cb;
}

typedef redisTimerCallback =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> timer,
        ffi.Pointer<ffi.Void> privdata,
      )
    >;

/// Result of a poll operation.
enum RedisPollResult {
  REDIS_POLL_TIMEOUT(0),
  REDIS_POLL_ACTIVITY(1),
  REDIS_POLL_ERROR(-1),
  REDIS_POLL_CLOSED(-2);

  final int value;
  const RedisPollResult(this.value);

  static RedisPollResult fromValue(int value) => switch (value) {
    0 => REDIS_POLL_TIMEOUT,
    1 => REDIS_POLL_ACTIVITY,
    -1 => REDIS_POLL_ERROR,
    -2 => REDIS_POLL_CLOSED,
    _ => throw ArgumentError('Unknown value for RedisPollResult: $value'),
  };
}

final class LoopThreadHandle extends ffi.Opaque {}

const int REDIS_ERR = -1;

const int REDIS_OK = 0;

const int REDIS_ERR_IO = 1;

const int REDIS_ERR_EOF = 3;

const int REDIS_ERR_PROTOCOL = 4;

const int REDIS_ERR_OOM = 5;

const int REDIS_ERR_TIMEOUT = 6;

const int REDIS_ERR_OTHER = 2;

const int REDIS_REPLY_STRING = 1;

const int REDIS_REPLY_ARRAY = 2;

const int REDIS_REPLY_INTEGER = 3;

const int REDIS_REPLY_NIL = 4;

const int REDIS_REPLY_STATUS = 5;

const int REDIS_REPLY_ERROR = 6;

const int REDIS_REPLY_DOUBLE = 7;

const int REDIS_REPLY_BOOL = 8;

const int REDIS_REPLY_MAP = 9;

const int REDIS_REPLY_SET = 10;

const int REDIS_REPLY_ATTR = 11;

const int REDIS_REPLY_PUSH = 12;

const int REDIS_REPLY_BIGNUM = 13;

const int REDIS_REPLY_VERB = 14;

const int REDIS_READER_MAX_BUF = 16384;

const int REDIS_READER_MAX_ARRAY_ELEMENTS = 4294967295;

const int HIREDIS_MAJOR = 1;

const int HIREDIS_MINOR = 3;

const int HIREDIS_PATCH = 0;

const int REDIS_BLOCK = 1;

const int REDIS_CONNECTED = 2;

const int REDIS_DISCONNECTING = 4;

const int REDIS_FREEING = 8;

const int REDIS_IN_CALLBACK = 16;

const int REDIS_SUBSCRIBED = 32;

const int REDIS_MONITORING = 64;

const int REDIS_REUSEADDR = 128;

const int REDIS_SUPPORTS_PUSH = 256;

const int REDIS_NO_AUTO_FREE = 512;

const int REDIS_NO_AUTO_FREE_REPLIES = 1024;

const int REDIS_PREFER_IPV4 = 2048;

const int REDIS_PREFER_IPV6 = 4096;

const int REDIS_KEEPALIVE_INTERVAL = 15;

const int REDIS_CONNECT_RETRIES = 10;

const int REDIS_OPT_NONBLOCK = 1;

const int REDIS_OPT_REUSEADDR = 2;

const int REDIS_OPT_NOAUTOFREE = 4;

const int REDIS_OPT_NO_PUSH_AUTOFREE = 8;

const int REDIS_OPT_NOAUTOFREEREPLIES = 16;

const int REDIS_OPT_PREFER_IPV4 = 32;

const int REDIS_OPT_PREFER_IPV6 = 64;

const int REDIS_OPT_PREFER_IP_UNSPEC = 96;

const int REDIS_INVALID_FD = -1;
