// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for hiredis C library
class HiredisBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  HiredisBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  HiredisBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<redisReader> redisReaderCreateWithFunctions(
    ffi.Pointer<redisReplyObjectFunctions> fn,
  ) {
    return _redisReaderCreateWithFunctions(fn);
  }

  late final _redisReaderCreateWithFunctionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisReader> Function(
            ffi.Pointer<redisReplyObjectFunctions>,
          )
        >
      >('redisReaderCreateWithFunctions');
  late final _redisReaderCreateWithFunctions =
      _redisReaderCreateWithFunctionsPtr
          .asFunction<
            ffi.Pointer<redisReader> Function(
              ffi.Pointer<redisReplyObjectFunctions>,
            )
          >();

  void redisReaderFree(ffi.Pointer<redisReader> r) {
    return _redisReaderFree(r);
  }

  late final _redisReaderFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisReader>)>>(
        'redisReaderFree',
      );
  late final _redisReaderFree = _redisReaderFreePtr
      .asFunction<void Function(ffi.Pointer<redisReader>)>();

  int redisReaderFeed(
    ffi.Pointer<redisReader> r,
    ffi.Pointer<ffi.Char> buf,
    int len,
  ) {
    return _redisReaderFeed(r, buf, len);
  }

  late final _redisReaderFeedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisReader>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redisReaderFeed');
  late final _redisReaderFeed = _redisReaderFeedPtr
      .asFunction<
        int Function(ffi.Pointer<redisReader>, ffi.Pointer<ffi.Char>, int)
      >();

  int redisReaderGetReply(
    ffi.Pointer<redisReader> r,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redisReaderGetReply(r, reply);
  }

  late final _redisReaderGetReplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisReader>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redisReaderGetReply');
  late final _redisReaderGetReply = _redisReaderGetReplyPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisReader>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  sds sdsnewlen(ffi.Pointer<ffi.Void> init, int initlen) {
    return _sdsnewlen(init, initlen);
  }

  late final _sdsnewlenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(ffi.Pointer<ffi.Void>, ffi.Size)>
      >('sdsnewlen');
  late final _sdsnewlen = _sdsnewlenPtr
      .asFunction<sds Function(ffi.Pointer<ffi.Void>, int)>();

  sds sdsnew(ffi.Pointer<ffi.Char> init) {
    return _sdsnew(init);
  }

  late final _sdsnewPtr =
      _lookup<ffi.NativeFunction<sds Function(ffi.Pointer<ffi.Char>)>>(
        'sdsnew',
      );
  late final _sdsnew = _sdsnewPtr
      .asFunction<sds Function(ffi.Pointer<ffi.Char>)>();

  sds sdsempty() {
    return _sdsempty();
  }

  late final _sdsemptyPtr = _lookup<ffi.NativeFunction<sds Function()>>(
    'sdsempty',
  );
  late final _sdsempty = _sdsemptyPtr.asFunction<sds Function()>();

  sds sdsdup(sds s) {
    return _sdsdup(s);
  }

  late final _sdsdupPtr = _lookup<ffi.NativeFunction<sds Function(sds)>>(
    'sdsdup',
  );
  late final _sdsdup = _sdsdupPtr.asFunction<sds Function(sds)>();

  void sdsfree(sds s) {
    return _sdsfree(s);
  }

  late final _sdsfreePtr = _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
    'sdsfree',
  );
  late final _sdsfree = _sdsfreePtr.asFunction<void Function(sds)>();

  sds sdsgrowzero(sds s, int len) {
    return _sdsgrowzero(s, len);
  }

  late final _sdsgrowzeroPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Size)>>('sdsgrowzero');
  late final _sdsgrowzero = _sdsgrowzeroPtr
      .asFunction<sds Function(sds, int)>();

  sds sdscatlen(sds s, ffi.Pointer<ffi.Void> t, int len) {
    return _sdscatlen(s, t, len);
  }

  late final _sdscatlenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Void>, ffi.Size)>
      >('sdscatlen');
  late final _sdscatlen = _sdscatlenPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Void>, int)>();

  sds sdscat(sds s, ffi.Pointer<ffi.Char> t) {
    return _sdscat(s, t);
  }

  late final _sdscatPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscat',
      );
  late final _sdscat = _sdscatPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatsds(sds s, sds t) {
    return _sdscatsds(s, t);
  }

  late final _sdscatsdsPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, sds)>>('sdscatsds');
  late final _sdscatsds = _sdscatsdsPtr.asFunction<sds Function(sds, sds)>();

  sds sdscpylen(sds s, ffi.Pointer<ffi.Char> t, int len) {
    return _sdscpylen(s, t, len);
  }

  late final _sdscpylenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>
      >('sdscpylen');
  late final _sdscpylen = _sdscpylenPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>, int)>();

  sds sdscpy(sds s, ffi.Pointer<ffi.Char> t) {
    return _sdscpy(s, t);
  }

  late final _sdscpyPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscpy',
      );
  late final _sdscpy = _sdscpyPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatvprintf(
    sds s,
    ffi.Pointer<ffi.Char> fmt,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _sdscatvprintf(s, fmt, ap);
  }

  late final _sdscatvprintfPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
        >
      >('sdscatvprintf');
  late final _sdscatvprintf = _sdscatvprintfPtr
      .asFunction<
        sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
      >();

  sds sdscatprintf(sds s, ffi.Pointer<ffi.Char> fmt) {
    return _sdscatprintf(s, fmt);
  }

  late final _sdscatprintfPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscatprintf',
      );
  late final _sdscatprintf = _sdscatprintfPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatfmt(sds s, ffi.Pointer<ffi.Char> fmt) {
    return _sdscatfmt(s, fmt);
  }

  late final _sdscatfmtPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscatfmt',
      );
  late final _sdscatfmt = _sdscatfmtPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdstrim(sds s, ffi.Pointer<ffi.Char> cset) {
    return _sdstrim(s, cset);
  }

  late final _sdstrimPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdstrim',
      );
  late final _sdstrim = _sdstrimPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  int sdsrange(sds s, int start, int end) {
    return _sdsrange(s, start, end);
  }

  late final _sdsrangePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(sds, ssize_t, ssize_t)>>(
        'sdsrange',
      );
  late final _sdsrange = _sdsrangePtr.asFunction<int Function(sds, int, int)>();

  void sdsupdatelen(sds s) {
    return _sdsupdatelen(s);
  }

  late final _sdsupdatelenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdsupdatelen');
  late final _sdsupdatelen = _sdsupdatelenPtr.asFunction<void Function(sds)>();

  void sdsclear(sds s) {
    return _sdsclear(s);
  }

  late final _sdsclearPtr = _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
    'sdsclear',
  );
  late final _sdsclear = _sdsclearPtr.asFunction<void Function(sds)>();

  int sdscmp(sds s1, sds s2) {
    return _sdscmp(s1, s2);
  }

  late final _sdscmpPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(sds, sds)>>('sdscmp');
  late final _sdscmp = _sdscmpPtr.asFunction<int Function(sds, sds)>();

  ffi.Pointer<sds> sdssplitlen(
    ffi.Pointer<ffi.Char> s,
    int len,
    ffi.Pointer<ffi.Char> sep,
    int seplen,
    ffi.Pointer<ffi.Int> count,
  ) {
    return _sdssplitlen(s, len, sep, seplen, count);
  }

  late final _sdssplitlenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<sds> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('sdssplitlen');
  late final _sdssplitlen = _sdssplitlenPtr
      .asFunction<
        ffi.Pointer<sds> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Int>,
        )
      >();

  void sdsfreesplitres(ffi.Pointer<sds> tokens, int count) {
    return _sdsfreesplitres(tokens, count);
  }

  late final _sdsfreesplitresPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<sds>, ffi.Int)>>(
        'sdsfreesplitres',
      );
  late final _sdsfreesplitres = _sdsfreesplitresPtr
      .asFunction<void Function(ffi.Pointer<sds>, int)>();

  void sdstolower(sds s) {
    return _sdstolower(s);
  }

  late final _sdstolowerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdstolower');
  late final _sdstolower = _sdstolowerPtr.asFunction<void Function(sds)>();

  void sdstoupper(sds s) {
    return _sdstoupper(s);
  }

  late final _sdstoupperPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdstoupper');
  late final _sdstoupper = _sdstoupperPtr.asFunction<void Function(sds)>();

  sds sdsfromlonglong(int value) {
    return _sdsfromlonglong(value);
  }

  late final _sdsfromlonglongPtr =
      _lookup<ffi.NativeFunction<sds Function(ffi.LongLong)>>(
        'sdsfromlonglong',
      );
  late final _sdsfromlonglong = _sdsfromlonglongPtr
      .asFunction<sds Function(int)>();

  sds sdscatrepr(sds s, ffi.Pointer<ffi.Char> p, int len) {
    return _sdscatrepr(s, p, len);
  }

  late final _sdscatreprPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>
      >('sdscatrepr');
  late final _sdscatrepr = _sdscatreprPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<sds> sdssplitargs(
    ffi.Pointer<ffi.Char> line,
    ffi.Pointer<ffi.Int> argc,
  ) {
    return _sdssplitargs(line, argc);
  }

  late final _sdssplitargsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<sds> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
        >
      >('sdssplitargs');
  late final _sdssplitargs = _sdssplitargsPtr
      .asFunction<
        ffi.Pointer<sds> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
      >();

  sds sdsmapchars(
    sds s,
    ffi.Pointer<ffi.Char> from,
    ffi.Pointer<ffi.Char> to,
    int setlen,
  ) {
    return _sdsmapchars(s, from, to, setlen);
  }

  late final _sdsmapcharsPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            sds,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('sdsmapchars');
  late final _sdsmapchars = _sdsmapcharsPtr
      .asFunction<
        sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  sds sdsjoin(
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    int argc,
    ffi.Pointer<ffi.Char> sep,
  ) {
    return _sdsjoin(argv, argc, sep);
  }

  late final _sdsjoinPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('sdsjoin');
  late final _sdsjoin = _sdsjoinPtr
      .asFunction<
        sds Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  sds sdsjoinsds(
    ffi.Pointer<sds> argv,
    int argc,
    ffi.Pointer<ffi.Char> sep,
    int seplen,
  ) {
    return _sdsjoinsds(argv, argc, sep, seplen);
  }

  late final _sdsjoinsdsPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            ffi.Pointer<sds>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('sdsjoinsds');
  late final _sdsjoinsds = _sdsjoinsdsPtr
      .asFunction<
        sds Function(ffi.Pointer<sds>, int, ffi.Pointer<ffi.Char>, int)
      >();

  sds sdsMakeRoomFor(sds s, int addlen) {
    return _sdsMakeRoomFor(s, addlen);
  }

  late final _sdsMakeRoomForPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Size)>>(
        'sdsMakeRoomFor',
      );
  late final _sdsMakeRoomFor = _sdsMakeRoomForPtr
      .asFunction<sds Function(sds, int)>();

  void sdsIncrLen(sds s, int incr) {
    return _sdsIncrLen(s, incr);
  }

  late final _sdsIncrLenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds, ffi.Int)>>(
        'sdsIncrLen',
      );
  late final _sdsIncrLen = _sdsIncrLenPtr.asFunction<void Function(sds, int)>();

  sds sdsRemoveFreeSpace(sds s) {
    return _sdsRemoveFreeSpace(s);
  }

  late final _sdsRemoveFreeSpacePtr =
      _lookup<ffi.NativeFunction<sds Function(sds)>>('sdsRemoveFreeSpace');
  late final _sdsRemoveFreeSpace = _sdsRemoveFreeSpacePtr
      .asFunction<sds Function(sds)>();

  int sdsAllocSize(sds s) {
    return _sdsAllocSize(s);
  }

  late final _sdsAllocSizePtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(sds)>>('sdsAllocSize');
  late final _sdsAllocSize = _sdsAllocSizePtr.asFunction<int Function(sds)>();

  ffi.Pointer<ffi.Void> sdsAllocPtr(sds s) {
    return _sdsAllocPtr(s);
  }

  late final _sdsAllocPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(sds)>>(
        'sdsAllocPtr',
      );
  late final _sdsAllocPtr = _sdsAllocPtrPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(sds)>();

  ffi.Pointer<ffi.Void> sds_malloc(int size) {
    return _sds_malloc(size);
  }

  late final _sds_mallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
        'sds_malloc',
      );
  late final _sds_malloc = _sds_mallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  ffi.Pointer<ffi.Void> sds_realloc(ffi.Pointer<ffi.Void> ptr, int size) {
    return _sds_realloc(ptr, size);
  }

  late final _sds_reallocPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('sds_realloc');
  late final _sds_realloc = _sds_reallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)>();

  void sds_free(ffi.Pointer<ffi.Void> ptr) {
    return _sds_free(ptr);
  }

  late final _sds_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'sds_free',
      );
  late final _sds_free = _sds_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  late final ffi.Pointer<hiredisAllocFuncs> _hiredisAllocFns =
      _lookup<hiredisAllocFuncs>('hiredisAllocFns');

  hiredisAllocFuncs get hiredisAllocFns => _hiredisAllocFns.ref;

  ffi.Pointer<redisReader> redisReaderCreate() {
    return _redisReaderCreate();
  }

  late final _redisReaderCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<redisReader> Function()>>(
        'redisReaderCreate',
      );
  late final _redisReaderCreate = _redisReaderCreatePtr
      .asFunction<ffi.Pointer<redisReader> Function()>();

  void freeReplyObject(ffi.Pointer<ffi.Void> reply) {
    return _freeReplyObject(reply);
  }

  late final _freeReplyObjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'freeReplyObject',
      );
  late final _freeReplyObject = _freeReplyObjectPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  int redisvFormatCommand(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redisvFormatCommand(target, format, ap);
  }

  late final _redisvFormatCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redisvFormatCommand');
  late final _redisvFormatCommand = _redisvFormatCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redisFormatCommand(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redisFormatCommand(target, format);
  }

  late final _redisFormatCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisFormatCommand');
  late final _redisFormatCommand = _redisFormatCommandPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
      >();

  int redisFormatCommandArgv(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redisFormatCommandArgv(target, argc, argv, argvlen);
  }

  late final _redisFormatCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redisFormatCommandArgv');
  late final _redisFormatCommandArgv = _redisFormatCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int redisFormatSdsCommandArgv(
    ffi.Pointer<sds> target,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redisFormatSdsCommandArgv(target, argc, argv, argvlen);
  }

  late final _redisFormatSdsCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<sds>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redisFormatSdsCommandArgv');
  late final _redisFormatSdsCommandArgv = _redisFormatSdsCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<sds>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void redisFreeCommand(ffi.Pointer<ffi.Char> cmd) {
    return _redisFreeCommand(cmd);
  }

  late final _redisFreeCommandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'redisFreeCommand',
      );
  late final _redisFreeCommand = _redisFreeCommandPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void redisFreeSdsCommand(sds cmd) {
    return _redisFreeSdsCommand(cmd);
  }

  late final _redisFreeSdsCommandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
        'redisFreeSdsCommand',
      );
  late final _redisFreeSdsCommand = _redisFreeSdsCommandPtr
      .asFunction<void Function(sds)>();

  ffi.Pointer<redisContext> redisConnectWithOptions(
    ffi.Pointer<redisOptions> options,
  ) {
    return _redisConnectWithOptions(options);
  }

  late final _redisConnectWithOptionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<redisOptions>)
        >
      >('redisConnectWithOptions');
  late final _redisConnectWithOptions = _redisConnectWithOptionsPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(ffi.Pointer<redisOptions>)
      >();

  ffi.Pointer<redisContext> redisConnect(ffi.Pointer<ffi.Char> ip, int port) {
    return _redisConnect(ip, port);
  }

  late final _redisConnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
        >
      >('redisConnect');
  late final _redisConnect = _redisConnectPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redisContext> redisConnectWithTimeout(
    ffi.Pointer<ffi.Char> ip,
    int port,
    timeval tv,
  ) {
    return _redisConnectWithTimeout(ip, port, tv);
  }

  late final _redisConnectWithTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            timeval,
          )
        >
      >('redisConnectWithTimeout');
  late final _redisConnectWithTimeout = _redisConnectWithTimeoutPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, int, timeval)
      >();

  ffi.Pointer<redisContext> redisConnectNonBlock(
    ffi.Pointer<ffi.Char> ip,
    int port,
  ) {
    return _redisConnectNonBlock(ip, port);
  }

  late final _redisConnectNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
        >
      >('redisConnectNonBlock');
  late final _redisConnectNonBlock = _redisConnectNonBlockPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redisContext> redisConnectBindNonBlock(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redisConnectBindNonBlock(ip, port, source_addr);
  }

  late final _redisConnectBindNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisConnectBindNonBlock');
  late final _redisConnectBindNonBlock = _redisConnectBindNonBlockPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<redisContext> redisConnectBindNonBlockWithReuse(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redisConnectBindNonBlockWithReuse(ip, port, source_addr);
  }

  late final _redisConnectBindNonBlockWithReusePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisConnectBindNonBlockWithReuse');
  late final _redisConnectBindNonBlockWithReuse =
      _redisConnectBindNonBlockWithReusePtr
          .asFunction<
            ffi.Pointer<redisContext> Function(
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<redisContext> redisConnectUnix(ffi.Pointer<ffi.Char> path) {
    return _redisConnectUnix(path);
  }

  late final _redisConnectUnixPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redisConnectUnix');
  late final _redisConnectUnix = _redisConnectUnixPtr
      .asFunction<ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<redisContext> redisConnectUnixWithTimeout(
    ffi.Pointer<ffi.Char> path,
    timeval tv,
  ) {
    return _redisConnectUnixWithTimeout(path, tv);
  }

  late final _redisConnectUnixWithTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, timeval)
        >
      >('redisConnectUnixWithTimeout');
  late final _redisConnectUnixWithTimeout = _redisConnectUnixWithTimeoutPtr
      .asFunction<
        ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>, timeval)
      >();

  ffi.Pointer<redisContext> redisConnectUnixNonBlock(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _redisConnectUnixNonBlock(path);
  }

  late final _redisConnectUnixNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redisConnectUnixNonBlock');
  late final _redisConnectUnixNonBlock = _redisConnectUnixNonBlockPtr
      .asFunction<ffi.Pointer<redisContext> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<redisContext> redisConnectFd(int fd) {
    return _redisConnectFd(fd);
  }

  late final _redisConnectFdPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<redisContext> Function(redisFD)>>(
        'redisConnectFd',
      );
  late final _redisConnectFd = _redisConnectFdPtr
      .asFunction<ffi.Pointer<redisContext> Function(int)>();

  /// Reconnect the given context using the saved information.
  ///
  /// This re-uses the exact same connect options as in the initial connection.
  /// host, ip (or path), timeout and bind address are reused,
  /// flags are used unmodified from the existing context.
  ///
  /// Returns REDIS_OK on successful connect or REDIS_ERR otherwise.
  int redisReconnect(ffi.Pointer<redisContext> c) {
    return _redisReconnect(c);
  }

  late final _redisReconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisContext>)>>(
        'redisReconnect',
      );
  late final _redisReconnect = _redisReconnectPtr
      .asFunction<int Function(ffi.Pointer<redisContext>)>();

  ffi.Pointer<redisPushFn> redisSetPushCallback(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<redisPushFn> fn,
  ) {
    return _redisSetPushCallback(c, fn);
  }

  late final _redisSetPushCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisPushFn> Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<redisPushFn>,
          )
        >
      >('redisSetPushCallback');
  late final _redisSetPushCallback = _redisSetPushCallbackPtr
      .asFunction<
        ffi.Pointer<redisPushFn> Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<redisPushFn>,
        )
      >();

  int redisSetTimeout(ffi.Pointer<redisContext> c, timeval tv) {
    return _redisSetTimeout(c, tv);
  }

  late final _redisSetTimeoutPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisContext>, timeval)>
      >('redisSetTimeout');
  late final _redisSetTimeout = _redisSetTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redisContext>, timeval)>();

  int redisEnableKeepAlive(ffi.Pointer<redisContext> c) {
    return _redisEnableKeepAlive(c);
  }

  late final _redisEnableKeepAlivePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisContext>)>>(
        'redisEnableKeepAlive',
      );
  late final _redisEnableKeepAlive = _redisEnableKeepAlivePtr
      .asFunction<int Function(ffi.Pointer<redisContext>)>();

  int redisEnableKeepAliveWithInterval(
    ffi.Pointer<redisContext> c,
    int interval,
  ) {
    return _redisEnableKeepAliveWithInterval(c, interval);
  }

  late final _redisEnableKeepAliveWithIntervalPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisContext>, ffi.Int)>
      >('redisEnableKeepAliveWithInterval');
  late final _redisEnableKeepAliveWithInterval =
      _redisEnableKeepAliveWithIntervalPtr
          .asFunction<int Function(ffi.Pointer<redisContext>, int)>();

  int redisSetTcpUserTimeout(ffi.Pointer<redisContext> c, int timeout) {
    return _redisSetTcpUserTimeout(c, timeout);
  }

  late final _redisSetTcpUserTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redisContext>, ffi.UnsignedInt)
        >
      >('redisSetTcpUserTimeout');
  late final _redisSetTcpUserTimeout = _redisSetTcpUserTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redisContext>, int)>();

  void redisFree(ffi.Pointer<redisContext> c) {
    return _redisFree(c);
  }

  late final _redisFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisContext>)>>(
        'redisFree',
      );
  late final _redisFree = _redisFreePtr
      .asFunction<void Function(ffi.Pointer<redisContext>)>();

  int redisFreeKeepFd(ffi.Pointer<redisContext> c) {
    return _redisFreeKeepFd(c);
  }

  late final _redisFreeKeepFdPtr =
      _lookup<ffi.NativeFunction<redisFD Function(ffi.Pointer<redisContext>)>>(
        'redisFreeKeepFd',
      );
  late final _redisFreeKeepFd = _redisFreeKeepFdPtr
      .asFunction<int Function(ffi.Pointer<redisContext>)>();

  int redisBufferRead(ffi.Pointer<redisContext> c) {
    return _redisBufferRead(c);
  }

  late final _redisBufferReadPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisContext>)>>(
        'redisBufferRead',
      );
  late final _redisBufferRead = _redisBufferReadPtr
      .asFunction<int Function(ffi.Pointer<redisContext>)>();

  int redisBufferWrite(ffi.Pointer<redisContext> c, ffi.Pointer<ffi.Int> done) {
    return _redisBufferWrite(c, done);
  }

  late final _redisBufferWritePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Int>)
        >
      >('redisBufferWrite');
  late final _redisBufferWrite = _redisBufferWritePtr
      .asFunction<
        int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Int>)
      >();

  int redisGetReply(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redisGetReply(c, reply);
  }

  late final _redisGetReplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redisGetReply');
  late final _redisGetReply = _redisGetReplyPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int redisGetReplyFromReader(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redisGetReplyFromReader(c, reply);
  }

  late final _redisGetReplyFromReaderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redisGetReplyFromReader');
  late final _redisGetReplyFromReader = _redisGetReplyFromReaderPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int redisAppendFormattedCommand(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Char> cmd,
    int len,
  ) {
    return _redisAppendFormattedCommand(c, cmd, len);
  }

  late final _redisAppendFormattedCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redisAppendFormattedCommand');
  late final _redisAppendFormattedCommand = _redisAppendFormattedCommandPtr
      .asFunction<
        int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Char>, int)
      >();

  int redisvAppendCommand(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redisvAppendCommand(c, format, ap);
  }

  late final _redisvAppendCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redisvAppendCommand');
  late final _redisvAppendCommand = _redisvAppendCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redisAppendCommand(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redisAppendCommand(c, format);
  }

  late final _redisAppendCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Char>)
        >
      >('redisAppendCommand');
  late final _redisAppendCommand = _redisAppendCommandPtr
      .asFunction<
        int Function(ffi.Pointer<redisContext>, ffi.Pointer<ffi.Char>)
      >();

  int redisAppendCommandArgv(
    ffi.Pointer<redisContext> c,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redisAppendCommandArgv(c, argc, argv, argvlen);
  }

  late final _redisAppendCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisContext>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redisAppendCommandArgv');
  late final _redisAppendCommandArgv = _redisAppendCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisContext>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> redisvCommand(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redisvCommand(c, format, ap);
  }

  late final _redisvCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redisvCommand');
  late final _redisvCommand = _redisvCommandPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  ffi.Pointer<ffi.Void> redisCommand(
    ffi.Pointer<redisContext> c,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redisCommand(c, format);
  }

  late final _redisCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redisContext>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisCommand');
  late final _redisCommand = _redisCommandPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redisContext>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Void> redisCommandArgv(
    ffi.Pointer<redisContext> c,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redisCommandArgv(c, argc, argv, argvlen);
  }

  late final _redisCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redisContext>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redisCommandArgv');
  late final _redisCommandArgv = _redisCommandArgvPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redisContext>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<redisAsyncContext> redisAsyncConnectWithOptions(
    ffi.Pointer<redisOptions> options,
  ) {
    return _redisAsyncConnectWithOptions(options);
  }

  late final _redisAsyncConnectWithOptionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<redisOptions>)
        >
      >('redisAsyncConnectWithOptions');
  late final _redisAsyncConnectWithOptions = _redisAsyncConnectWithOptionsPtr
      .asFunction<
        ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<redisOptions>)
      >();

  ffi.Pointer<redisAsyncContext> redisAsyncConnect(
    ffi.Pointer<ffi.Char> ip,
    int port,
  ) {
    return _redisAsyncConnect(ip, port);
  }

  late final _redisAsyncConnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('redisAsyncConnect');
  late final _redisAsyncConnect = _redisAsyncConnectPtr
      .asFunction<
        ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redisAsyncContext> redisAsyncConnectBind(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redisAsyncConnectBind(ip, port, source_addr);
  }

  late final _redisAsyncConnectBindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisAsyncConnectBind');
  late final _redisAsyncConnectBind = _redisAsyncConnectBindPtr
      .asFunction<
        ffi.Pointer<redisAsyncContext> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<redisAsyncContext> redisAsyncConnectBindWithReuse(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redisAsyncConnectBindWithReuse(ip, port, source_addr);
  }

  late final _redisAsyncConnectBindWithReusePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisAsyncConnectBindWithReuse');
  late final _redisAsyncConnectBindWithReuse =
      _redisAsyncConnectBindWithReusePtr
          .asFunction<
            ffi.Pointer<redisAsyncContext> Function(
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<redisAsyncContext> redisAsyncConnectUnix(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _redisAsyncConnectUnix(path);
  }

  late final _redisAsyncConnectUnixPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redisAsyncConnectUnix');
  late final _redisAsyncConnectUnix = _redisAsyncConnectUnixPtr
      .asFunction<
        ffi.Pointer<redisAsyncContext> Function(ffi.Pointer<ffi.Char>)
      >();

  int redisAsyncSetConnectCallback(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisConnectCallback> fn,
  ) {
    return _redisAsyncSetConnectCallback(ac, fn);
  }

  late final _redisAsyncSetConnectCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisConnectCallback>,
          )
        >
      >('redisAsyncSetConnectCallback');
  late final _redisAsyncSetConnectCallback = _redisAsyncSetConnectCallbackPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisConnectCallback>,
        )
      >();

  int redisAsyncSetConnectCallbackNC(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisConnectCallbackNC> fn,
  ) {
    return _redisAsyncSetConnectCallbackNC(ac, fn);
  }

  late final _redisAsyncSetConnectCallbackNCPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisConnectCallbackNC>,
          )
        >
      >('redisAsyncSetConnectCallbackNC');
  late final _redisAsyncSetConnectCallbackNC =
      _redisAsyncSetConnectCallbackNCPtr
          .asFunction<
            int Function(
              ffi.Pointer<redisAsyncContext>,
              ffi.Pointer<redisConnectCallbackNC>,
            )
          >();

  int redisAsyncSetDisconnectCallback(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisDisconnectCallback> fn,
  ) {
    return _redisAsyncSetDisconnectCallback(ac, fn);
  }

  late final _redisAsyncSetDisconnectCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisDisconnectCallback>,
          )
        >
      >('redisAsyncSetDisconnectCallback');
  late final _redisAsyncSetDisconnectCallback =
      _redisAsyncSetDisconnectCallbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<redisAsyncContext>,
              ffi.Pointer<redisDisconnectCallback>,
            )
          >();

  ffi.Pointer<redisAsyncPushFn> redisAsyncSetPushCallback(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisAsyncPushFn> fn,
  ) {
    return _redisAsyncSetPushCallback(ac, fn);
  }

  late final _redisAsyncSetPushCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redisAsyncPushFn> Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisAsyncPushFn>,
          )
        >
      >('redisAsyncSetPushCallback');
  late final _redisAsyncSetPushCallback = _redisAsyncSetPushCallbackPtr
      .asFunction<
        ffi.Pointer<redisAsyncPushFn> Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisAsyncPushFn>,
        )
      >();

  int redisAsyncSetTimeout(ffi.Pointer<redisAsyncContext> ac, timeval tv) {
    return _redisAsyncSetTimeout(ac, tv);
  }

  late final _redisAsyncSetTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redisAsyncContext>, timeval)
        >
      >('redisAsyncSetTimeout');
  late final _redisAsyncSetTimeout = _redisAsyncSetTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redisAsyncContext>, timeval)>();

  void redisAsyncDisconnect(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncDisconnect(ac);
  }

  late final _redisAsyncDisconnectPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncDisconnect');
  late final _redisAsyncDisconnect = _redisAsyncDisconnectPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncFree(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncFree(ac);
  }

  late final _redisAsyncFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncFree');
  late final _redisAsyncFree = _redisAsyncFreePtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncHandleRead(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncHandleRead(ac);
  }

  late final _redisAsyncHandleReadPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncHandleRead');
  late final _redisAsyncHandleRead = _redisAsyncHandleReadPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncHandleWrite(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncHandleWrite(ac);
  }

  late final _redisAsyncHandleWritePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncHandleWrite');
  late final _redisAsyncHandleWrite = _redisAsyncHandleWritePtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncHandleTimeout(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncHandleTimeout(ac);
  }

  late final _redisAsyncHandleTimeoutPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncHandleTimeout');
  late final _redisAsyncHandleTimeout = _redisAsyncHandleTimeoutPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncRead(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncRead(ac);
  }

  late final _redisAsyncReadPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncRead');
  late final _redisAsyncRead = _redisAsyncReadPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  void redisAsyncWrite(ffi.Pointer<redisAsyncContext> ac) {
    return _redisAsyncWrite(ac);
  }

  late final _redisAsyncWritePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redisAsyncWrite');
  late final _redisAsyncWrite = _redisAsyncWritePtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();

  int redisvAsyncCommand(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redisvAsyncCommand(ac, fn, privdata, format, ap);
  }

  late final _redisvAsyncCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redisvAsyncCommand');
  late final _redisvAsyncCommand = _redisvAsyncCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redisAsyncCommand(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redisAsyncCommand(ac, fn, privdata, format);
  }

  late final _redisAsyncCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redisAsyncCommand');
  late final _redisAsyncCommand = _redisAsyncCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int redisAsyncCommandArgv(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redisAsyncCommandArgv(ac, fn, privdata, argc, argv, argvlen);
  }

  late final _redisAsyncCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redisAsyncCommandArgv');
  late final _redisAsyncCommandArgv = _redisAsyncCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisCallbackFn>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int redisAsyncFormattedCommand(
    ffi.Pointer<redisAsyncContext> ac,
    ffi.Pointer<redisCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> cmd,
    int len,
  ) {
    return _redisAsyncFormattedCommand(ac, fn, privdata, cmd, len);
  }

  late final _redisAsyncFormattedCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redisAsyncContext>,
            ffi.Pointer<redisCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redisAsyncFormattedCommand');
  late final _redisAsyncFormattedCommand = _redisAsyncFormattedCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redisAsyncContext>,
          ffi.Pointer<redisCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  /// Polls the Redis async context for I/O readiness and handles events.
  ///
  /// This function blocks until:
  /// - Data is available to read
  /// - The socket is ready for writing (and we have data to write)
  /// - The timeout expires
  /// - An error occurs
  ///
  /// @param ctx The async context to poll.
  /// @param timeout_ms Timeout in milliseconds. Use -1 for infinite wait.
  /// @return Poll result code.
  RedisPollResult redis_async_poll(
    ffi.Pointer<redisAsyncContext> ctx,
    int timeout_ms,
  ) {
    return RedisPollResult.fromValue(_redis_async_poll(ctx, timeout_ms));
  }

  late final _redis_async_pollPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
        >
      >('redis_async_poll');
  late final _redis_async_poll = _redis_async_pollPtr
      .asFunction<int Function(ffi.Pointer<redisAsyncContext>, int)>();

  /// Starts a polling loop in the current thread.
  ///
  /// This function runs until:
  /// - The context is disconnected
  /// - An unrecoverable error occurs
  ///
  /// @param ctx The async context to run the loop for.
  /// @param poll_interval_ms Timeout for each poll iteration.
  void redis_async_run_loop(
    ffi.Pointer<redisAsyncContext> ctx,
    int poll_interval_ms,
  ) {
    return _redis_async_run_loop(ctx, poll_interval_ms);
  }

  late final _redis_async_run_loopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
        >
      >('redis_async_run_loop');
  late final _redis_async_run_loop = _redis_async_run_loopPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>, int)>();

  /// Gets the file descriptor from an async context.
  /// @return The fd, or -1 if the context is null or disconnected.
  int redis_async_get_fd(ffi.Pointer<redisAsyncContext> ctx) {
    return _redis_async_get_fd(ctx);
  }

  late final _redis_async_get_fdPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redisAsyncContext>)>
      >('redis_async_get_fd');
  late final _redis_async_get_fd = _redis_async_get_fdPtr
      .asFunction<int Function(ffi.Pointer<redisAsyncContext>)>();

  /// Checks if the async context is connected.
  /// @return true if connected, false otherwise.
  bool redis_async_is_connected(ffi.Pointer<redisAsyncContext> ctx) {
    return _redis_async_is_connected(ctx);
  }

  late final _redis_async_is_connectedPtr =
      _lookup<
        ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<redisAsyncContext>)>
      >('redis_async_is_connected');
  late final _redis_async_is_connected = _redis_async_is_connectedPtr
      .asFunction<bool Function(ffi.Pointer<redisAsyncContext>)>();

  /// Forces a write flush - sends any pending commands immediately.
  void redis_async_flush(ffi.Pointer<redisAsyncContext> ctx) {
    return _redis_async_flush(ctx);
  }

  late final _redis_async_flushPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
      >('redis_async_flush');
  late final _redis_async_flush = _redis_async_flushPtr
      .asFunction<void Function(ffi.Pointer<redisAsyncContext>)>();
}

final class redisReadTask extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int elements;

  @ffi.Int()
  external int idx;

  external ffi.Pointer<ffi.Void> obj;

  external ffi.Pointer<redisReadTask> parent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redisReplyObjectFunctions extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redisReadTask>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createString;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.Size)
    >
  >
  createArray;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.LongLong)
    >
  >
  createInteger;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redisReadTask>,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createDouble;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>)
    >
  >
  createNil;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redisReadTask>, ffi.Int)
    >
  >
  createBool;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeObject;
}

final class redisReader extends ffi.Struct {
  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  external ffi.Pointer<ffi.Char> buf;

  @ffi.Size()
  external int pos;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int maxbuf;

  @ffi.LongLong()
  external int maxelements;

  external ffi.Pointer<ffi.Pointer<redisReadTask>> task;

  @ffi.Int()
  external int tasks;

  @ffi.Int()
  external int ridx;

  external ffi.Pointer<ffi.Void> reply;

  external ffi.Pointer<redisReplyObjectFunctions> fn;

  external ffi.Pointer<ffi.Void> privdata;
}

typedef sds = ffi.Pointer<ffi.Char>;

final class __va_list_tag extends ffi.Struct {
  @ffi.UnsignedInt()
  external int gp_offset;

  @ffi.UnsignedInt()
  external int fp_offset;

  external ffi.Pointer<ffi.Void> overflow_arg_area;

  external ffi.Pointer<ffi.Void> reg_save_area;
}

typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef ssize_t = __darwin_ssize_t;

final class hiredisAllocFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>
  >
  mallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>
  >
  callocFn;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
    >
  >
  reallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>
  >
  strdupFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeFn;
}

final class redisContextFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisContext>)>
  >
  close;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privctx;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
  >
  async_read;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redisAsyncContext>)>
  >
  async_write;

  external ffi.Pointer<
    ffi.NativeFunction<
      ssize_t Function(
        ffi.Pointer<redisContext>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  read;

  external ffi.Pointer<
    ffi.NativeFunction<ssize_t Function(ffi.Pointer<redisContext>)>
  >
  write;
}

typedef redisFD = ffi.Int;
typedef DartredisFD = int;

enum redisConnectionType {
  REDIS_CONN_TCP(0),
  REDIS_CONN_UNIX(1),
  REDIS_CONN_USERFD(2);

  final int value;
  const redisConnectionType(this.value);

  static redisConnectionType fromValue(int value) => switch (value) {
    0 => REDIS_CONN_TCP,
    1 => REDIS_CONN_UNIX,
    2 => REDIS_CONN_USERFD,
    _ => throw ArgumentError('Unknown value for redisConnectionType: $value'),
  };
}

typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __darwin_suseconds_t = __int32_t;

final class timeval extends ffi.Struct {
  @__darwin_time_t()
  external int tv_sec;

  @__darwin_suseconds_t()
  external int tv_usec;
}

final class UnnamedStruct$2 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> host;

  external ffi.Pointer<ffi.Char> source_addr;

  @ffi.Int()
  external int port;
}

final class UnnamedStruct$3 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> path;
}

final class sockaddr extends ffi.Opaque {}

typedef redisPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >;

final class redisContext extends ffi.Struct {
  external ffi.Pointer<redisContextFuncs> funcs;

  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  @redisFD()
  external int fd;

  @ffi.Int()
  external int flags;

  external ffi.Pointer<ffi.Char> obuf;

  external ffi.Pointer<redisReader> reader;

  @ffi.UnsignedInt()
  external int connection_typeAsInt;

  redisConnectionType get connection_type =>
      redisConnectionType.fromValue(connection_typeAsInt);

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedStruct$2 tcp;

  external UnnamedStruct$3 unix_sock;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<ffi.Void> privctx;

  external ffi.Pointer<redisPushFn> push_cb;
}

final class UnnamedStruct extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  cleanup;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> privdata, timeval tv)
    >
  >
  scheduleTimer;
}

typedef redisDisconnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisConnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisConnectCallbackNC =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Int)
    >;
typedef redisCallbackFn =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<redisAsyncContext>,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Void>,
      )
    >;

final class redisCallback extends ffi.Struct {
  external ffi.Pointer<redisCallback> next;

  external ffi.Pointer<redisCallbackFn> fn;

  @ffi.Int()
  external int pending_subs;

  @ffi.Int()
  external int unsubscribe_sent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redisCallbackList extends ffi.Struct {
  external ffi.Pointer<redisCallback> head;

  external ffi.Pointer<redisCallback> tail;
}

final class dict extends ffi.Opaque {}

final class UnnamedStruct$1 extends ffi.Struct {
  external redisCallbackList replies;

  external ffi.Pointer<dict> channels;

  external ffi.Pointer<dict> patterns;

  @ffi.Int()
  external int pending_unsubs;
}

typedef redisAsyncPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redisAsyncContext>, ffi.Pointer<ffi.Void>)
    >;

final class redisAsyncContext extends ffi.Struct {
  external redisContext c;

  @ffi.Int()
  external int err;

  external ffi.Pointer<ffi.Char> errstr;

  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  dataCleanup;

  external UnnamedStruct ev;

  external ffi.Pointer<redisDisconnectCallback> onDisconnect;

  external ffi.Pointer<redisConnectCallback> onConnect;

  external ffi.Pointer<redisConnectCallbackNC> onConnectNC;

  external redisCallbackList replies;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external UnnamedStruct$1 sub;

  external ffi.Pointer<redisAsyncPushFn> push_cb;
}

final class redisReply extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int integer;

  @ffi.Double()
  external double dval;

  @ffi.Size()
  external int len;

  external ffi.Pointer<ffi.Char> str;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> vtype;

  @ffi.Size()
  external int elements;

  external ffi.Pointer<ffi.Pointer<redisReply>> element;
}

/// use this field for tcp/ip connections
final class UnnamedStruct$4 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> source_addr;

  external ffi.Pointer<ffi.Char> ip;

  @ffi.Int()
  external int port;
}

final class UnnamedUnion extends ffi.Union {
  external UnnamedStruct$4 tcp;

  /// use this field for unix domain sockets
  external ffi.Pointer<ffi.Char> unix_socket;

  /// use this field to have hiredis operate an already-open
  /// file descriptor
  @redisFD()
  external int fd;
}

final class redisOptions extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.Int()
  external int options;

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedUnion endpoint;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<redisPushFn> push_cb;

  external ffi.Pointer<redisAsyncPushFn> async_push_cb;
}

typedef redisTimerCallback =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> timer,
        ffi.Pointer<ffi.Void> privdata,
      )
    >;

/// Result of a poll operation.
enum RedisPollResult {
  REDIS_POLL_TIMEOUT(0),
  REDIS_POLL_ACTIVITY(1),
  REDIS_POLL_ERROR(-1),
  REDIS_POLL_CLOSED(-2);

  final int value;
  const RedisPollResult(this.value);

  static RedisPollResult fromValue(int value) => switch (value) {
    0 => REDIS_POLL_TIMEOUT,
    1 => REDIS_POLL_ACTIVITY,
    -1 => REDIS_POLL_ERROR,
    -2 => REDIS_POLL_CLOSED,
    _ => throw ArgumentError('Unknown value for RedisPollResult: $value'),
  };
}

const int REDIS_ERR = -1;

const int REDIS_OK = 0;

const int REDIS_ERR_IO = 1;

const int REDIS_ERR_EOF = 3;

const int REDIS_ERR_PROTOCOL = 4;

const int REDIS_ERR_OOM = 5;

const int REDIS_ERR_TIMEOUT = 6;

const int REDIS_ERR_OTHER = 2;

const int REDIS_REPLY_STRING = 1;

const int REDIS_REPLY_ARRAY = 2;

const int REDIS_REPLY_INTEGER = 3;

const int REDIS_REPLY_NIL = 4;

const int REDIS_REPLY_STATUS = 5;

const int REDIS_REPLY_ERROR = 6;

const int REDIS_REPLY_DOUBLE = 7;

const int REDIS_REPLY_BOOL = 8;

const int REDIS_REPLY_MAP = 9;

const int REDIS_REPLY_SET = 10;

const int REDIS_REPLY_ATTR = 11;

const int REDIS_REPLY_PUSH = 12;

const int REDIS_REPLY_BIGNUM = 13;

const int REDIS_REPLY_VERB = 14;

const int REDIS_READER_MAX_BUF = 16384;

const int REDIS_READER_MAX_ARRAY_ELEMENTS = 4294967295;

const int HIREDIS_MAJOR = 1;

const int HIREDIS_MINOR = 3;

const int HIREDIS_PATCH = 0;

const int REDIS_BLOCK = 1;

const int REDIS_CONNECTED = 2;

const int REDIS_DISCONNECTING = 4;

const int REDIS_FREEING = 8;

const int REDIS_IN_CALLBACK = 16;

const int REDIS_SUBSCRIBED = 32;

const int REDIS_MONITORING = 64;

const int REDIS_REUSEADDR = 128;

const int REDIS_SUPPORTS_PUSH = 256;

const int REDIS_NO_AUTO_FREE = 512;

const int REDIS_NO_AUTO_FREE_REPLIES = 1024;

const int REDIS_PREFER_IPV4 = 2048;

const int REDIS_PREFER_IPV6 = 4096;

const int REDIS_KEEPALIVE_INTERVAL = 15;

const int REDIS_CONNECT_RETRIES = 10;

const int REDIS_OPT_NONBLOCK = 1;

const int REDIS_OPT_REUSEADDR = 2;

const int REDIS_OPT_NOAUTOFREE = 4;

const int REDIS_OPT_NO_PUSH_AUTOFREE = 8;

const int REDIS_OPT_NOAUTOFREEREPLIES = 16;

const int REDIS_OPT_PREFER_IPV4 = 32;

const int REDIS_OPT_PREFER_IPV6 = 64;

const int REDIS_OPT_PREFER_IP_UNSPEC = 96;

const int REDIS_INVALID_FD = -1;
