// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for hiredict (hiredis fork) C library
class HiredisBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  HiredisBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  HiredisBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<redictReader> redictReaderCreateWithFunctions(
    ffi.Pointer<redictReplyObjectFunctions> fn,
  ) {
    return _redictReaderCreateWithFunctions(fn);
  }

  late final _redictReaderCreateWithFunctionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictReader> Function(
            ffi.Pointer<redictReplyObjectFunctions>,
          )
        >
      >('redictReaderCreateWithFunctions');
  late final _redictReaderCreateWithFunctions =
      _redictReaderCreateWithFunctionsPtr
          .asFunction<
            ffi.Pointer<redictReader> Function(
              ffi.Pointer<redictReplyObjectFunctions>,
            )
          >();

  void redictReaderFree(ffi.Pointer<redictReader> r) {
    return _redictReaderFree(r);
  }

  late final _redictReaderFreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictReader>)>>(
        'redictReaderFree',
      );
  late final _redictReaderFree = _redictReaderFreePtr
      .asFunction<void Function(ffi.Pointer<redictReader>)>();

  int redictReaderFeed(
    ffi.Pointer<redictReader> r,
    ffi.Pointer<ffi.Char> buf,
    int len,
  ) {
    return _redictReaderFeed(r, buf, len);
  }

  late final _redictReaderFeedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictReader>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redictReaderFeed');
  late final _redictReaderFeed = _redictReaderFeedPtr
      .asFunction<
        int Function(ffi.Pointer<redictReader>, ffi.Pointer<ffi.Char>, int)
      >();

  int redictReaderGetReply(
    ffi.Pointer<redictReader> r,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redictReaderGetReply(r, reply);
  }

  late final _redictReaderGetReplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictReader>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redictReaderGetReply');
  late final _redictReaderGetReply = _redictReaderGetReplyPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictReader>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  sds sdsnewlen(ffi.Pointer<ffi.Void> init, int initlen) {
    return _sdsnewlen(init, initlen);
  }

  late final _sdsnewlenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(ffi.Pointer<ffi.Void>, ffi.Size)>
      >('sdsnewlen');
  late final _sdsnewlen = _sdsnewlenPtr
      .asFunction<sds Function(ffi.Pointer<ffi.Void>, int)>();

  sds sdsnew(ffi.Pointer<ffi.Char> init) {
    return _sdsnew(init);
  }

  late final _sdsnewPtr =
      _lookup<ffi.NativeFunction<sds Function(ffi.Pointer<ffi.Char>)>>(
        'sdsnew',
      );
  late final _sdsnew = _sdsnewPtr
      .asFunction<sds Function(ffi.Pointer<ffi.Char>)>();

  sds sdsempty() {
    return _sdsempty();
  }

  late final _sdsemptyPtr = _lookup<ffi.NativeFunction<sds Function()>>(
    'sdsempty',
  );
  late final _sdsempty = _sdsemptyPtr.asFunction<sds Function()>();

  sds sdsdup(sds s) {
    return _sdsdup(s);
  }

  late final _sdsdupPtr = _lookup<ffi.NativeFunction<sds Function(sds)>>(
    'sdsdup',
  );
  late final _sdsdup = _sdsdupPtr.asFunction<sds Function(sds)>();

  void sdsfree(sds s) {
    return _sdsfree(s);
  }

  late final _sdsfreePtr = _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
    'sdsfree',
  );
  late final _sdsfree = _sdsfreePtr.asFunction<void Function(sds)>();

  sds sdsgrowzero(sds s, int len) {
    return _sdsgrowzero(s, len);
  }

  late final _sdsgrowzeroPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Size)>>('sdsgrowzero');
  late final _sdsgrowzero = _sdsgrowzeroPtr
      .asFunction<sds Function(sds, int)>();

  sds sdscatlen(sds s, ffi.Pointer<ffi.Void> t, int len) {
    return _sdscatlen(s, t, len);
  }

  late final _sdscatlenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Void>, ffi.Size)>
      >('sdscatlen');
  late final _sdscatlen = _sdscatlenPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Void>, int)>();

  sds sdscat(sds s, ffi.Pointer<ffi.Char> t) {
    return _sdscat(s, t);
  }

  late final _sdscatPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscat',
      );
  late final _sdscat = _sdscatPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatsds(sds s, sds t) {
    return _sdscatsds(s, t);
  }

  late final _sdscatsdsPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, sds)>>('sdscatsds');
  late final _sdscatsds = _sdscatsdsPtr.asFunction<sds Function(sds, sds)>();

  sds sdscpylen(sds s, ffi.Pointer<ffi.Char> t, int len) {
    return _sdscpylen(s, t, len);
  }

  late final _sdscpylenPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>
      >('sdscpylen');
  late final _sdscpylen = _sdscpylenPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>, int)>();

  sds sdscpy(sds s, ffi.Pointer<ffi.Char> t) {
    return _sdscpy(s, t);
  }

  late final _sdscpyPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscpy',
      );
  late final _sdscpy = _sdscpyPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatvprintf(
    sds s,
    ffi.Pointer<ffi.Char> fmt,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _sdscatvprintf(s, fmt, ap);
  }

  late final _sdscatvprintfPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
        >
      >('sdscatvprintf');
  late final _sdscatvprintf = _sdscatvprintfPtr
      .asFunction<
        sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<__va_list_tag>)
      >();

  sds sdscatprintf(sds s, ffi.Pointer<ffi.Char> fmt) {
    return _sdscatprintf(s, fmt);
  }

  late final _sdscatprintfPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscatprintf',
      );
  late final _sdscatprintf = _sdscatprintfPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdscatfmt(sds s, ffi.Pointer<ffi.Char> fmt) {
    return _sdscatfmt(s, fmt);
  }

  late final _sdscatfmtPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdscatfmt',
      );
  late final _sdscatfmt = _sdscatfmtPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  sds sdstrim(sds s, ffi.Pointer<ffi.Char> cset) {
    return _sdstrim(s, cset);
  }

  late final _sdstrimPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>>(
        'sdstrim',
      );
  late final _sdstrim = _sdstrimPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>)>();

  int sdsrange(sds s, int start, int end) {
    return _sdsrange(s, start, end);
  }

  late final _sdsrangePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(sds, ssize_t, ssize_t)>>(
        'sdsrange',
      );
  late final _sdsrange = _sdsrangePtr.asFunction<int Function(sds, int, int)>();

  void sdsupdatelen(sds s) {
    return _sdsupdatelen(s);
  }

  late final _sdsupdatelenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdsupdatelen');
  late final _sdsupdatelen = _sdsupdatelenPtr.asFunction<void Function(sds)>();

  void sdsclear(sds s) {
    return _sdsclear(s);
  }

  late final _sdsclearPtr = _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
    'sdsclear',
  );
  late final _sdsclear = _sdsclearPtr.asFunction<void Function(sds)>();

  int sdscmp(sds s1, sds s2) {
    return _sdscmp(s1, s2);
  }

  late final _sdscmpPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(sds, sds)>>('sdscmp');
  late final _sdscmp = _sdscmpPtr.asFunction<int Function(sds, sds)>();

  ffi.Pointer<sds> sdssplitlen(
    ffi.Pointer<ffi.Char> s,
    int len,
    ffi.Pointer<ffi.Char> sep,
    int seplen,
    ffi.Pointer<ffi.Int> count,
  ) {
    return _sdssplitlen(s, len, sep, seplen, count);
  }

  late final _sdssplitlenPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<sds> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('sdssplitlen');
  late final _sdssplitlen = _sdssplitlenPtr
      .asFunction<
        ffi.Pointer<sds> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Int>,
        )
      >();

  void sdsfreesplitres(ffi.Pointer<sds> tokens, int count) {
    return _sdsfreesplitres(tokens, count);
  }

  late final _sdsfreesplitresPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<sds>, ffi.Int)>>(
        'sdsfreesplitres',
      );
  late final _sdsfreesplitres = _sdsfreesplitresPtr
      .asFunction<void Function(ffi.Pointer<sds>, int)>();

  void sdstolower(sds s) {
    return _sdstolower(s);
  }

  late final _sdstolowerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdstolower');
  late final _sdstolower = _sdstolowerPtr.asFunction<void Function(sds)>();

  void sdstoupper(sds s) {
    return _sdstoupper(s);
  }

  late final _sdstoupperPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>('sdstoupper');
  late final _sdstoupper = _sdstoupperPtr.asFunction<void Function(sds)>();

  sds sdsfromlonglong(int value) {
    return _sdsfromlonglong(value);
  }

  late final _sdsfromlonglongPtr =
      _lookup<ffi.NativeFunction<sds Function(ffi.LongLong)>>(
        'sdsfromlonglong',
      );
  late final _sdsfromlonglong = _sdsfromlonglongPtr
      .asFunction<sds Function(int)>();

  sds sdscatrepr(sds s, ffi.Pointer<ffi.Char> p, int len) {
    return _sdscatrepr(s, p, len);
  }

  late final _sdscatreprPtr =
      _lookup<
        ffi.NativeFunction<sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Size)>
      >('sdscatrepr');
  late final _sdscatrepr = _sdscatreprPtr
      .asFunction<sds Function(sds, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<sds> sdssplitargs(
    ffi.Pointer<ffi.Char> line,
    ffi.Pointer<ffi.Int> argc,
  ) {
    return _sdssplitargs(line, argc);
  }

  late final _sdssplitargsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<sds> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
        >
      >('sdssplitargs');
  late final _sdssplitargs = _sdssplitargsPtr
      .asFunction<
        ffi.Pointer<sds> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
      >();

  sds sdsmapchars(
    sds s,
    ffi.Pointer<ffi.Char> from,
    ffi.Pointer<ffi.Char> to,
    int setlen,
  ) {
    return _sdsmapchars(s, from, to, setlen);
  }

  late final _sdsmapcharsPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            sds,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('sdsmapchars');
  late final _sdsmapchars = _sdsmapcharsPtr
      .asFunction<
        sds Function(sds, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  sds sdsjoin(
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    int argc,
    ffi.Pointer<ffi.Char> sep,
  ) {
    return _sdsjoin(argv, argc, sep);
  }

  late final _sdsjoinPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('sdsjoin');
  late final _sdsjoin = _sdsjoinPtr
      .asFunction<
        sds Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  sds sdsjoinsds(
    ffi.Pointer<sds> argv,
    int argc,
    ffi.Pointer<ffi.Char> sep,
    int seplen,
  ) {
    return _sdsjoinsds(argv, argc, sep, seplen);
  }

  late final _sdsjoinsdsPtr =
      _lookup<
        ffi.NativeFunction<
          sds Function(
            ffi.Pointer<sds>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('sdsjoinsds');
  late final _sdsjoinsds = _sdsjoinsdsPtr
      .asFunction<
        sds Function(ffi.Pointer<sds>, int, ffi.Pointer<ffi.Char>, int)
      >();

  sds sdsMakeRoomFor(sds s, int addlen) {
    return _sdsMakeRoomFor(s, addlen);
  }

  late final _sdsMakeRoomForPtr =
      _lookup<ffi.NativeFunction<sds Function(sds, ffi.Size)>>(
        'sdsMakeRoomFor',
      );
  late final _sdsMakeRoomFor = _sdsMakeRoomForPtr
      .asFunction<sds Function(sds, int)>();

  void sdsIncrLen(sds s, int incr) {
    return _sdsIncrLen(s, incr);
  }

  late final _sdsIncrLenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds, ffi.Int)>>(
        'sdsIncrLen',
      );
  late final _sdsIncrLen = _sdsIncrLenPtr.asFunction<void Function(sds, int)>();

  sds sdsRemoveFreeSpace(sds s) {
    return _sdsRemoveFreeSpace(s);
  }

  late final _sdsRemoveFreeSpacePtr =
      _lookup<ffi.NativeFunction<sds Function(sds)>>('sdsRemoveFreeSpace');
  late final _sdsRemoveFreeSpace = _sdsRemoveFreeSpacePtr
      .asFunction<sds Function(sds)>();

  int sdsAllocSize(sds s) {
    return _sdsAllocSize(s);
  }

  late final _sdsAllocSizePtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(sds)>>('sdsAllocSize');
  late final _sdsAllocSize = _sdsAllocSizePtr.asFunction<int Function(sds)>();

  ffi.Pointer<ffi.Void> sdsAllocPtr(sds s) {
    return _sdsAllocPtr(s);
  }

  late final _sdsAllocPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(sds)>>(
        'sdsAllocPtr',
      );
  late final _sdsAllocPtr = _sdsAllocPtrPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(sds)>();

  ffi.Pointer<ffi.Void> sds_malloc(int size) {
    return _sds_malloc(size);
  }

  late final _sds_mallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
        'sds_malloc',
      );
  late final _sds_malloc = _sds_mallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  ffi.Pointer<ffi.Void> sds_realloc(ffi.Pointer<ffi.Void> ptr, int size) {
    return _sds_realloc(ptr, size);
  }

  late final _sds_reallocPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('sds_realloc');
  late final _sds_realloc = _sds_reallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)>();

  void sds_free(ffi.Pointer<ffi.Void> ptr) {
    return _sds_free(ptr);
  }

  late final _sds_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'sds_free',
      );
  late final _sds_free = _sds_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  late final ffi.Pointer<hiredictAllocFuncs> _hiredictAllocFns =
      _lookup<hiredictAllocFuncs>('hiredictAllocFns');

  hiredictAllocFuncs get hiredictAllocFns => _hiredictAllocFns.ref;

  ffi.Pointer<redictReader> redictReaderCreate() {
    return _redictReaderCreate();
  }

  late final _redictReaderCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<redictReader> Function()>>(
        'redictReaderCreate',
      );
  late final _redictReaderCreate = _redictReaderCreatePtr
      .asFunction<ffi.Pointer<redictReader> Function()>();

  void freeReplyObject(ffi.Pointer<ffi.Void> reply) {
    return _freeReplyObject(reply);
  }

  late final _freeReplyObjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'freeReplyObject',
      );
  late final _freeReplyObject = _freeReplyObjectPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  int redictvFormatCommand(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redictvFormatCommand(target, format, ap);
  }

  late final _redictvFormatCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redictvFormatCommand');
  late final _redictvFormatCommand = _redictvFormatCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redictFormatCommand(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redictFormatCommand(target, format);
  }

  late final _redictFormatCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictFormatCommand');
  late final _redictFormatCommand = _redictFormatCommandPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Pointer<ffi.Char>)
      >();

  int redictFormatCommandArgv(
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redictFormatCommandArgv(target, argc, argv, argvlen);
  }

  late final _redictFormatCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redictFormatCommandArgv');
  late final _redictFormatCommandArgv = _redictFormatCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int redictFormatSdsCommandArgv(
    ffi.Pointer<sds> target,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redictFormatSdsCommandArgv(target, argc, argv, argvlen);
  }

  late final _redictFormatSdsCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<sds>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redictFormatSdsCommandArgv');
  late final _redictFormatSdsCommandArgv = _redictFormatSdsCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<sds>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void redictFreeCommand(ffi.Pointer<ffi.Char> cmd) {
    return _redictFreeCommand(cmd);
  }

  late final _redictFreeCommandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'redictFreeCommand',
      );
  late final _redictFreeCommand = _redictFreeCommandPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void redictFreeSdsCommand(sds cmd) {
    return _redictFreeSdsCommand(cmd);
  }

  late final _redictFreeSdsCommandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(sds)>>(
        'redictFreeSdsCommand',
      );
  late final _redictFreeSdsCommand = _redictFreeSdsCommandPtr
      .asFunction<void Function(sds)>();

  ffi.Pointer<redictContext> redictConnectWithOptions(
    ffi.Pointer<redictOptions> options,
  ) {
    return _redictConnectWithOptions(options);
  }

  late final _redictConnectWithOptionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<redictOptions>)
        >
      >('redictConnectWithOptions');
  late final _redictConnectWithOptions = _redictConnectWithOptionsPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(ffi.Pointer<redictOptions>)
      >();

  ffi.Pointer<redictContext> redictConnect(ffi.Pointer<ffi.Char> ip, int port) {
    return _redictConnect(ip, port);
  }

  late final _redictConnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
        >
      >('redictConnect');
  late final _redictConnect = _redictConnectPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redictContext> redictConnectWithTimeout(
    ffi.Pointer<ffi.Char> ip,
    int port,
    timeval tv,
  ) {
    return _redictConnectWithTimeout(ip, port, tv);
  }

  late final _redictConnectWithTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            timeval,
          )
        >
      >('redictConnectWithTimeout');
  late final _redictConnectWithTimeout = _redictConnectWithTimeoutPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, int, timeval)
      >();

  ffi.Pointer<redictContext> redictConnectNonBlock(
    ffi.Pointer<ffi.Char> ip,
    int port,
  ) {
    return _redictConnectNonBlock(ip, port);
  }

  late final _redictConnectNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, ffi.Int)
        >
      >('redictConnectNonBlock');
  late final _redictConnectNonBlock = _redictConnectNonBlockPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redictContext> redictConnectBindNonBlock(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redictConnectBindNonBlock(ip, port, source_addr);
  }

  late final _redictConnectBindNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictConnectBindNonBlock');
  late final _redictConnectBindNonBlock = _redictConnectBindNonBlockPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<redictContext> redictConnectBindNonBlockWithReuse(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redictConnectBindNonBlockWithReuse(ip, port, source_addr);
  }

  late final _redictConnectBindNonBlockWithReusePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictConnectBindNonBlockWithReuse');
  late final _redictConnectBindNonBlockWithReuse =
      _redictConnectBindNonBlockWithReusePtr
          .asFunction<
            ffi.Pointer<redictContext> Function(
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<redictContext> redictConnectUnix(ffi.Pointer<ffi.Char> path) {
    return _redictConnectUnix(path);
  }

  late final _redictConnectUnixPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redictConnectUnix');
  late final _redictConnectUnix = _redictConnectUnixPtr
      .asFunction<ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<redictContext> redictConnectUnixWithTimeout(
    ffi.Pointer<ffi.Char> path,
    timeval tv,
  ) {
    return _redictConnectUnixWithTimeout(path, tv);
  }

  late final _redictConnectUnixWithTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, timeval)
        >
      >('redictConnectUnixWithTimeout');
  late final _redictConnectUnixWithTimeout = _redictConnectUnixWithTimeoutPtr
      .asFunction<
        ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>, timeval)
      >();

  ffi.Pointer<redictContext> redictConnectUnixNonBlock(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _redictConnectUnixNonBlock(path);
  }

  late final _redictConnectUnixNonBlockPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redictConnectUnixNonBlock');
  late final _redictConnectUnixNonBlock = _redictConnectUnixNonBlockPtr
      .asFunction<ffi.Pointer<redictContext> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<redictContext> redictConnectFd(int fd) {
    return _redictConnectFd(fd);
  }

  late final _redictConnectFdPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<redictContext> Function(redictFD)>
      >('redictConnectFd');
  late final _redictConnectFd = _redictConnectFdPtr
      .asFunction<ffi.Pointer<redictContext> Function(int)>();

  /// Reconnect the given context using the saved information.
  ///
  /// This re-uses the exact same connect options as in the initial connection.
  /// host, ip (or path), timeout and bind address are reused,
  /// flags are used unmodified from the existing context.
  ///
  /// Returns REDICT_OK on successful connect or REDICT_ERR otherwise.
  int redictReconnect(ffi.Pointer<redictContext> c) {
    return _redictReconnect(c);
  }

  late final _redictReconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redictContext>)>>(
        'redictReconnect',
      );
  late final _redictReconnect = _redictReconnectPtr
      .asFunction<int Function(ffi.Pointer<redictContext>)>();

  ffi.Pointer<redictPushFn> redictSetPushCallback(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<redictPushFn> fn,
  ) {
    return _redictSetPushCallback(c, fn);
  }

  late final _redictSetPushCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictPushFn> Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<redictPushFn>,
          )
        >
      >('redictSetPushCallback');
  late final _redictSetPushCallback = _redictSetPushCallbackPtr
      .asFunction<
        ffi.Pointer<redictPushFn> Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<redictPushFn>,
        )
      >();

  int redictSetTimeout(ffi.Pointer<redictContext> c, timeval tv) {
    return _redictSetTimeout(c, tv);
  }

  late final _redictSetTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictContext>, timeval)
        >
      >('redictSetTimeout');
  late final _redictSetTimeout = _redictSetTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redictContext>, timeval)>();

  int redictEnableKeepAlive(ffi.Pointer<redictContext> c) {
    return _redictEnableKeepAlive(c);
  }

  late final _redictEnableKeepAlivePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redictContext>)>>(
        'redictEnableKeepAlive',
      );
  late final _redictEnableKeepAlive = _redictEnableKeepAlivePtr
      .asFunction<int Function(ffi.Pointer<redictContext>)>();

  int redictEnableKeepAliveWithInterval(
    ffi.Pointer<redictContext> c,
    int interval,
  ) {
    return _redictEnableKeepAliveWithInterval(c, interval);
  }

  late final _redictEnableKeepAliveWithIntervalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictContext>, ffi.Int)
        >
      >('redictEnableKeepAliveWithInterval');
  late final _redictEnableKeepAliveWithInterval =
      _redictEnableKeepAliveWithIntervalPtr
          .asFunction<int Function(ffi.Pointer<redictContext>, int)>();

  int redictSetTcpUserTimeout(ffi.Pointer<redictContext> c, int timeout) {
    return _redictSetTcpUserTimeout(c, timeout);
  }

  late final _redictSetTcpUserTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictContext>, ffi.UnsignedInt)
        >
      >('redictSetTcpUserTimeout');
  late final _redictSetTcpUserTimeout = _redictSetTcpUserTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redictContext>, int)>();

  void redictFree(ffi.Pointer<redictContext> c) {
    return _redictFree(c);
  }

  late final _redictFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictContext>)>
      >('redictFree');
  late final _redictFree = _redictFreePtr
      .asFunction<void Function(ffi.Pointer<redictContext>)>();

  int redictFreeKeepFd(ffi.Pointer<redictContext> c) {
    return _redictFreeKeepFd(c);
  }

  late final _redictFreeKeepFdPtr =
      _lookup<
        ffi.NativeFunction<redictFD Function(ffi.Pointer<redictContext>)>
      >('redictFreeKeepFd');
  late final _redictFreeKeepFd = _redictFreeKeepFdPtr
      .asFunction<int Function(ffi.Pointer<redictContext>)>();

  int redictBufferRead(ffi.Pointer<redictContext> c) {
    return _redictBufferRead(c);
  }

  late final _redictBufferReadPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<redictContext>)>>(
        'redictBufferRead',
      );
  late final _redictBufferRead = _redictBufferReadPtr
      .asFunction<int Function(ffi.Pointer<redictContext>)>();

  int redictBufferWrite(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Int> done,
  ) {
    return _redictBufferWrite(c, done);
  }

  late final _redictBufferWritePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictContext>, ffi.Pointer<ffi.Int>)
        >
      >('redictBufferWrite');
  late final _redictBufferWrite = _redictBufferWritePtr
      .asFunction<
        int Function(ffi.Pointer<redictContext>, ffi.Pointer<ffi.Int>)
      >();

  int redictGetReply(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redictGetReply(c, reply);
  }

  late final _redictGetReplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redictGetReply');
  late final _redictGetReply = _redictGetReplyPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int redictGetReplyFromReader(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Void>> reply,
  ) {
    return _redictGetReplyFromReader(c, reply);
  }

  late final _redictGetReplyFromReaderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('redictGetReplyFromReader');
  late final _redictGetReplyFromReader = _redictGetReplyFromReaderPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  int redictAppendFormattedCommand(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Char> cmd,
    int len,
  ) {
    return _redictAppendFormattedCommand(c, cmd, len);
  }

  late final _redictAppendFormattedCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redictAppendFormattedCommand');
  late final _redictAppendFormattedCommand = _redictAppendFormattedCommandPtr
      .asFunction<
        int Function(ffi.Pointer<redictContext>, ffi.Pointer<ffi.Char>, int)
      >();

  int redictvAppendCommand(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redictvAppendCommand(c, format, ap);
  }

  late final _redictvAppendCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redictvAppendCommand');
  late final _redictvAppendCommand = _redictvAppendCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redictAppendCommand(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redictAppendCommand(c, format);
  }

  late final _redictAppendCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictContext>, ffi.Pointer<ffi.Char>)
        >
      >('redictAppendCommand');
  late final _redictAppendCommand = _redictAppendCommandPtr
      .asFunction<
        int Function(ffi.Pointer<redictContext>, ffi.Pointer<ffi.Char>)
      >();

  int redictAppendCommandArgv(
    ffi.Pointer<redictContext> c,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redictAppendCommandArgv(c, argc, argv, argvlen);
  }

  late final _redictAppendCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictContext>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redictAppendCommandArgv');
  late final _redictAppendCommandArgv = _redictAppendCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictContext>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> redictvCommand(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redictvCommand(c, format, ap);
  }

  late final _redictvCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redictvCommand');
  late final _redictvCommand = _redictvCommandPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  ffi.Pointer<ffi.Void> redictCommand(
    ffi.Pointer<redictContext> c,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redictCommand(c, format);
  }

  late final _redictCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redictContext>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictCommand');
  late final _redictCommand = _redictCommandPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redictContext>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Void> redictCommandArgv(
    ffi.Pointer<redictContext> c,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redictCommandArgv(c, argc, argv, argvlen);
  }

  late final _redictCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<redictContext>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redictCommandArgv');
  late final _redictCommandArgv = _redictCommandArgvPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<redictContext>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<redictAsyncContext> redictAsyncConnectWithOptions(
    ffi.Pointer<redictOptions> options,
  ) {
    return _redictAsyncConnectWithOptions(options);
  }

  late final _redictAsyncConnectWithOptionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncContext> Function(ffi.Pointer<redictOptions>)
        >
      >('redictAsyncConnectWithOptions');
  late final _redictAsyncConnectWithOptions = _redictAsyncConnectWithOptionsPtr
      .asFunction<
        ffi.Pointer<redictAsyncContext> Function(ffi.Pointer<redictOptions>)
      >();

  ffi.Pointer<redictAsyncContext> redictAsyncConnect(
    ffi.Pointer<ffi.Char> ip,
    int port,
  ) {
    return _redictAsyncConnect(ip, port);
  }

  late final _redictAsyncConnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('redictAsyncConnect');
  late final _redictAsyncConnect = _redictAsyncConnectPtr
      .asFunction<
        ffi.Pointer<redictAsyncContext> Function(ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<redictAsyncContext> redictAsyncConnectBind(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redictAsyncConnectBind(ip, port, source_addr);
  }

  late final _redictAsyncConnectBindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictAsyncConnectBind');
  late final _redictAsyncConnectBind = _redictAsyncConnectBindPtr
      .asFunction<
        ffi.Pointer<redictAsyncContext> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<redictAsyncContext> redictAsyncConnectBindWithReuse(
    ffi.Pointer<ffi.Char> ip,
    int port,
    ffi.Pointer<ffi.Char> source_addr,
  ) {
    return _redictAsyncConnectBindWithReuse(ip, port, source_addr);
  }

  late final _redictAsyncConnectBindWithReusePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncContext> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictAsyncConnectBindWithReuse');
  late final _redictAsyncConnectBindWithReuse =
      _redictAsyncConnectBindWithReusePtr
          .asFunction<
            ffi.Pointer<redictAsyncContext> Function(
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<redictAsyncContext> redictAsyncConnectUnix(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _redictAsyncConnectUnix(path);
  }

  late final _redictAsyncConnectUnixPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncContext> Function(ffi.Pointer<ffi.Char>)
        >
      >('redictAsyncConnectUnix');
  late final _redictAsyncConnectUnix = _redictAsyncConnectUnixPtr
      .asFunction<
        ffi.Pointer<redictAsyncContext> Function(ffi.Pointer<ffi.Char>)
      >();

  int redictAsyncSetConnectCallback(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictConnectCallback> fn,
  ) {
    return _redictAsyncSetConnectCallback(ac, fn);
  }

  late final _redictAsyncSetConnectCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictConnectCallback>,
          )
        >
      >('redictAsyncSetConnectCallback');
  late final _redictAsyncSetConnectCallback = _redictAsyncSetConnectCallbackPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictConnectCallback>,
        )
      >();

  int redictAsyncSetConnectCallbackNC(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictConnectCallbackNC> fn,
  ) {
    return _redictAsyncSetConnectCallbackNC(ac, fn);
  }

  late final _redictAsyncSetConnectCallbackNCPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictConnectCallbackNC>,
          )
        >
      >('redictAsyncSetConnectCallbackNC');
  late final _redictAsyncSetConnectCallbackNC =
      _redictAsyncSetConnectCallbackNCPtr
          .asFunction<
            int Function(
              ffi.Pointer<redictAsyncContext>,
              ffi.Pointer<redictConnectCallbackNC>,
            )
          >();

  int redictAsyncSetDisconnectCallback(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictDisconnectCallback> fn,
  ) {
    return _redictAsyncSetDisconnectCallback(ac, fn);
  }

  late final _redictAsyncSetDisconnectCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictDisconnectCallback>,
          )
        >
      >('redictAsyncSetDisconnectCallback');
  late final _redictAsyncSetDisconnectCallback =
      _redictAsyncSetDisconnectCallbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<redictAsyncContext>,
              ffi.Pointer<redictDisconnectCallback>,
            )
          >();

  ffi.Pointer<redictAsyncPushFn> redictAsyncSetPushCallback(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictAsyncPushFn> fn,
  ) {
    return _redictAsyncSetPushCallback(ac, fn);
  }

  late final _redictAsyncSetPushCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<redictAsyncPushFn> Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictAsyncPushFn>,
          )
        >
      >('redictAsyncSetPushCallback');
  late final _redictAsyncSetPushCallback = _redictAsyncSetPushCallbackPtr
      .asFunction<
        ffi.Pointer<redictAsyncPushFn> Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictAsyncPushFn>,
        )
      >();

  int redictAsyncSetTimeout(ffi.Pointer<redictAsyncContext> ac, timeval tv) {
    return _redictAsyncSetTimeout(ac, tv);
  }

  late final _redictAsyncSetTimeoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<redictAsyncContext>, timeval)
        >
      >('redictAsyncSetTimeout');
  late final _redictAsyncSetTimeout = _redictAsyncSetTimeoutPtr
      .asFunction<int Function(ffi.Pointer<redictAsyncContext>, timeval)>();

  void redictAsyncDisconnect(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncDisconnect(ac);
  }

  late final _redictAsyncDisconnectPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncDisconnect');
  late final _redictAsyncDisconnect = _redictAsyncDisconnectPtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncFree(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncFree(ac);
  }

  late final _redictAsyncFreePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncFree');
  late final _redictAsyncFree = _redictAsyncFreePtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncHandleRead(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncHandleRead(ac);
  }

  late final _redictAsyncHandleReadPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncHandleRead');
  late final _redictAsyncHandleRead = _redictAsyncHandleReadPtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncHandleWrite(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncHandleWrite(ac);
  }

  late final _redictAsyncHandleWritePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncHandleWrite');
  late final _redictAsyncHandleWrite = _redictAsyncHandleWritePtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncHandleTimeout(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncHandleTimeout(ac);
  }

  late final _redictAsyncHandleTimeoutPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncHandleTimeout');
  late final _redictAsyncHandleTimeout = _redictAsyncHandleTimeoutPtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncRead(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncRead(ac);
  }

  late final _redictAsyncReadPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncRead');
  late final _redictAsyncRead = _redictAsyncReadPtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  void redictAsyncWrite(ffi.Pointer<redictAsyncContext> ac) {
    return _redictAsyncWrite(ac);
  }

  late final _redictAsyncWritePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
      >('redictAsyncWrite');
  late final _redictAsyncWrite = _redictAsyncWritePtr
      .asFunction<void Function(ffi.Pointer<redictAsyncContext>)>();

  int redictvAsyncCommand(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> format,
    ffi.Pointer<__va_list_tag> ap,
  ) {
    return _redictvAsyncCommand(ac, fn, privdata, format, ap);
  }

  late final _redictvAsyncCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<__va_list_tag>,
          )
        >
      >('redictvAsyncCommand');
  late final _redictvAsyncCommand = _redictvAsyncCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<__va_list_tag>,
        )
      >();

  int redictAsyncCommand(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> format,
  ) {
    return _redictAsyncCommand(ac, fn, privdata, format);
  }

  late final _redictAsyncCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('redictAsyncCommand');
  late final _redictAsyncCommand = _redictAsyncCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int redictAsyncCommandArgv(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    int argc,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Size> argvlen,
  ) {
    return _redictAsyncCommandArgv(ac, fn, privdata, argc, argv, argvlen);
  }

  late final _redictAsyncCommandArgvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('redictAsyncCommandArgv');
  late final _redictAsyncCommandArgv = _redictAsyncCommandArgvPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictCallbackFn>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int redictAsyncFormattedCommand(
    ffi.Pointer<redictAsyncContext> ac,
    ffi.Pointer<redictCallbackFn> fn,
    ffi.Pointer<ffi.Void> privdata,
    ffi.Pointer<ffi.Char> cmd,
    int len,
  ) {
    return _redictAsyncFormattedCommand(ac, fn, privdata, cmd, len);
  }

  late final _redictAsyncFormattedCommandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<redictAsyncContext>,
            ffi.Pointer<redictCallbackFn>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('redictAsyncFormattedCommand');
  late final _redictAsyncFormattedCommand = _redictAsyncFormattedCommandPtr
      .asFunction<
        int Function(
          ffi.Pointer<redictAsyncContext>,
          ffi.Pointer<redictCallbackFn>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();
}

final class redictReadTask extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int elements;

  @ffi.Int()
  external int idx;

  external ffi.Pointer<ffi.Void> obj;

  external ffi.Pointer<redictReadTask> parent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redictReplyObjectFunctions extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redictReadTask>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createString;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redictReadTask>, ffi.Size)
    >
  >
  createArray;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redictReadTask>, ffi.LongLong)
    >
  >
  createInteger;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<redictReadTask>,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  createDouble;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redictReadTask>)
    >
  >
  createNil;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<redictReadTask>, ffi.Int)
    >
  >
  createBool;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeObject;
}

final class redictReader extends ffi.Struct {
  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  external ffi.Pointer<ffi.Char> buf;

  @ffi.Size()
  external int pos;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int maxbuf;

  @ffi.LongLong()
  external int maxelements;

  external ffi.Pointer<ffi.Pointer<redictReadTask>> task;

  @ffi.Int()
  external int tasks;

  @ffi.Int()
  external int ridx;

  external ffi.Pointer<ffi.Void> reply;

  external ffi.Pointer<redictReplyObjectFunctions> fn;

  external ffi.Pointer<ffi.Void> privdata;
}

typedef sds = ffi.Pointer<ffi.Char>;

final class __va_list_tag extends ffi.Struct {
  @ffi.UnsignedInt()
  external int gp_offset;

  @ffi.UnsignedInt()
  external int fp_offset;

  external ffi.Pointer<ffi.Void> overflow_arg_area;

  external ffi.Pointer<ffi.Void> reg_save_area;
}

typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef ssize_t = __darwin_ssize_t;

final class hiredictAllocFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>
  >
  mallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>
  >
  callocFn;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
    >
  >
  reallocFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>
  >
  strdupFn;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  freeFn;
}

final class redictContextFuncs extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictContext>)>
  >
  close;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privctx;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
  >
  async_read;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<redictAsyncContext>)>
  >
  async_write;

  external ffi.Pointer<
    ffi.NativeFunction<
      ssize_t Function(
        ffi.Pointer<redictContext>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
      )
    >
  >
  read;

  external ffi.Pointer<
    ffi.NativeFunction<ssize_t Function(ffi.Pointer<redictContext>)>
  >
  write;
}

typedef redictFD = ffi.Int;
typedef DartredictFD = int;

enum redictConnectionType {
  REDICT_CONN_TCP(0),
  REDICT_CONN_UNIX(1),
  REDICT_CONN_USERFD(2);

  final int value;
  const redictConnectionType(this.value);

  static redictConnectionType fromValue(int value) => switch (value) {
    0 => REDICT_CONN_TCP,
    1 => REDICT_CONN_UNIX,
    2 => REDICT_CONN_USERFD,
    _ => throw ArgumentError('Unknown value for redictConnectionType: $value'),
  };
}

typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __darwin_suseconds_t = __int32_t;

final class timeval extends ffi.Struct {
  @__darwin_time_t()
  external int tv_sec;

  @__darwin_suseconds_t()
  external int tv_usec;
}

final class UnnamedStruct$2 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> host;

  external ffi.Pointer<ffi.Char> source_addr;

  @ffi.Int()
  external int port;
}

final class UnnamedStruct$3 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> path;
}

final class sockaddr extends ffi.Opaque {}

typedef redictPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >;

final class redictContext extends ffi.Struct {
  external ffi.Pointer<redictContextFuncs> funcs;

  @ffi.Int()
  external int err;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> errstr;

  @redictFD()
  external int fd;

  @ffi.Int()
  external int flags;

  external ffi.Pointer<ffi.Char> obuf;

  external ffi.Pointer<redictReader> reader;

  @ffi.UnsignedInt()
  external int connection_typeAsInt;

  redictConnectionType get connection_type =>
      redictConnectionType.fromValue(connection_typeAsInt);

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedStruct$2 tcp;

  external UnnamedStruct$3 unix_sock;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<ffi.Void> privctx;

  external ffi.Pointer<redictPushFn> push_cb;
}

final class UnnamedStruct extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delRead;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  addWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  delWrite;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  cleanup;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> privdata, timeval tv)
    >
  >
  scheduleTimer;
}

typedef redictDisconnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redictAsyncContext>, ffi.Int)
    >;
typedef redictConnectCallback =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redictAsyncContext>, ffi.Int)
    >;
typedef redictConnectCallbackNC =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redictAsyncContext>, ffi.Int)
    >;
typedef redictCallbackFn =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<redictAsyncContext>,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.Void>,
      )
    >;

final class redictCallback extends ffi.Struct {
  external ffi.Pointer<redictCallback> next;

  external ffi.Pointer<redictCallbackFn> fn;

  @ffi.Int()
  external int pending_subs;

  @ffi.Int()
  external int unsubscribe_sent;

  external ffi.Pointer<ffi.Void> privdata;
}

final class redictCallbackList extends ffi.Struct {
  external ffi.Pointer<redictCallback> head;

  external ffi.Pointer<redictCallback> tail;
}

final class dict extends ffi.Opaque {}

final class UnnamedStruct$1 extends ffi.Struct {
  external redictCallbackList replies;

  external ffi.Pointer<dict> channels;

  external ffi.Pointer<dict> patterns;

  @ffi.Int()
  external int pending_unsubs;
}

typedef redictAsyncPushFn =
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<redictAsyncContext>, ffi.Pointer<ffi.Void>)
    >;

final class redictAsyncContext extends ffi.Struct {
  external redictContext c;

  @ffi.Int()
  external int err;

  external ffi.Pointer<ffi.Char> errstr;

  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> privdata)>
  >
  dataCleanup;

  external UnnamedStruct ev;

  external ffi.Pointer<redictDisconnectCallback> onDisconnect;

  external ffi.Pointer<redictConnectCallback> onConnect;

  external ffi.Pointer<redictConnectCallbackNC> onConnectNC;

  external redictCallbackList replies;

  external ffi.Pointer<sockaddr> saddr;

  @ffi.Size()
  external int addrlen;

  external UnnamedStruct$1 sub;

  external ffi.Pointer<redictAsyncPushFn> push_cb;
}

final class redictReply extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.LongLong()
  external int integer;

  @ffi.Double()
  external double dval;

  @ffi.Size()
  external int len;

  external ffi.Pointer<ffi.Char> str;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> vtype;

  @ffi.Size()
  external int elements;

  external ffi.Pointer<ffi.Pointer<redictReply>> element;
}

/// use this field for tcp/ip connections
final class UnnamedStruct$4 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> source_addr;

  external ffi.Pointer<ffi.Char> ip;

  @ffi.Int()
  external int port;
}

final class UnnamedUnion extends ffi.Union {
  external UnnamedStruct$4 tcp;

  /// use this field for unix domain sockets
  external ffi.Pointer<ffi.Char> unix_socket;

  /// use this field to have hiredict operate an already-open
  /// file descriptor
  @redictFD()
  external int fd;
}

final class redictOptions extends ffi.Struct {
  @ffi.Int()
  external int type;

  @ffi.Int()
  external int options;

  external ffi.Pointer<timeval> connect_timeout;

  external ffi.Pointer<timeval> command_timeout;

  external UnnamedUnion endpoint;

  external ffi.Pointer<ffi.Void> privdata;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  free_privdata;

  external ffi.Pointer<redictPushFn> push_cb;

  external ffi.Pointer<redictAsyncPushFn> async_push_cb;
}

typedef redictTimerCallback =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> timer,
        ffi.Pointer<ffi.Void> privdata,
      )
    >;

const int REDICT_ERR = -1;

const int REDICT_OK = 0;

const int REDICT_ERR_IO = 1;

const int REDICT_ERR_EOF = 3;

const int REDICT_ERR_PROTOCOL = 4;

const int REDICT_ERR_OOM = 5;

const int REDICT_ERR_TIMEOUT = 6;

const int REDICT_ERR_OTHER = 2;

const int REDICT_REPLY_STRING = 1;

const int REDICT_REPLY_ARRAY = 2;

const int REDICT_REPLY_INTEGER = 3;

const int REDICT_REPLY_NIL = 4;

const int REDICT_REPLY_STATUS = 5;

const int REDICT_REPLY_ERROR = 6;

const int REDICT_REPLY_DOUBLE = 7;

const int REDICT_REPLY_BOOL = 8;

const int REDICT_REPLY_MAP = 9;

const int REDICT_REPLY_SET = 10;

const int REDICT_REPLY_ATTR = 11;

const int REDICT_REPLY_PUSH = 12;

const int REDICT_REPLY_BIGNUM = 13;

const int REDICT_REPLY_VERB = 14;

const int REDICT_READER_MAX_BUF = 16384;

const int REDICT_READER_MAX_ARRAY_ELEMENTS = 4294967295;

const int HIREDICT_MAJOR = 1;

const int HIREDICT_MINOR = 3;

const int HIREDICT_PATCH = 1;

const int REDICT_BLOCK = 1;

const int REDICT_CONNECTED = 2;

const int REDICT_DISCONNECTING = 4;

const int REDICT_FREEING = 8;

const int REDICT_IN_CALLBACK = 16;

const int REDICT_SUBSCRIBED = 32;

const int REDICT_MONITORING = 64;

const int REDICT_REUSEADDR = 128;

const int REDICT_SUPPORTS_PUSH = 256;

const int REDICT_NO_AUTO_FREE = 512;

const int REDICT_NO_AUTO_FREE_REPLIES = 1024;

const int REDICT_PREFER_IPV4 = 2048;

const int REDICT_PREFER_IPV6 = 4096;

const int REDICT_KEEPALIVE_INTERVAL = 15;

const int REDICT_CONNECT_RETRIES = 10;

const int REDICT_OPT_NONBLOCK = 1;

const int REDICT_OPT_REUSEADDR = 2;

const int REDICT_OPT_NOAUTOFREE = 4;

const int REDICT_OPT_NO_PUSH_AUTOFREE = 8;

const int REDICT_OPT_NOAUTOFREEREPLIES = 16;

const int REDICT_OPT_PREFER_IPV4 = 32;

const int REDICT_OPT_PREFER_IPV6 = 64;

const int REDICT_OPT_PREFER_IP_UNSPEC = 96;

const int REDICT_INVALID_FD = -1;
